Repository centrifuge/centrifuge-chain, pull requests merged in 2022-08, with the labels that each got.

#899 All ids in common-types
  Cargo.lock
  flake.nix
  libs/common-types/src/ids.rs
  libs/common-types/src/lib.rs
  pallets/bridge-mapping/Cargo.toml
  pallets/bridge-mapping/src/mock.rs
  pallets/bridge/Cargo.toml
  pallets/bridge/src/mock.rs
  pallets/claims/Cargo.toml
  pallets/claims/src/mock.rs
  pallets/crowdloan-claim/Cargo.toml
  pallets/crowdloan-claim/src/mock.rs
  pallets/crowdloan-reward/Cargo.toml
  pallets/crowdloan-reward/src/mock.rs
  pallets/loans/src/mock.rs
  pallets/nft-sales/Cargo.toml
  pallets/nft-sales/src/mock.rs
  pallets/nft/Cargo.toml
  pallets/nft/src/mock.rs
  pallets/pools/src/mock.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
Labels: D0-ready

#900 At at-param to rpc calls
  src/rpc/anchors.rs
  src/rpc/pools.rs
Labels: D5-breaks-api

#906 Removes the default `LoanType`
  pallets/loans/src/loan_type.rs
  pallets/pools/Cargo.toml
Labels: D0-ready

#886 Filter tranche transfers
  Cargo.lock
  flake.nix
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/xcm.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/xcm.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/xcm.rs
  runtime/integration-tests/src/xcm/kusama/mod.rs
  runtime/integration-tests/src/xcm/kusama/restricted_calls.rs
  runtime/integration-tests/src/xcm/polkadot/tests/asset_registry.rs
  runtime/integration-tests/src/xcm/polkadot/tests/mod.rs
  runtime/integration-tests/src/xcm/polkadot/tests/restricted_calls.rs
Labels: crcl-runtime, crcl-protocol, dependencies
