Repository centrifuge/centrifuge-chain, pull requests merged in 2022-10, with the labels that each got.

#983 Validate interest rates and limit the total count
  libs/traits/src/lib.rs
  pallets/interest-accrual/src/lib.rs
  pallets/interest-accrual/src/mock.rs
  pallets/interest-accrual/src/tests.rs
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/functions.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/mock.rs
  pallets/loans/src/tests.rs
  pallets/loans/src/types.rs
  runtime/altair/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/pools/utils/loans.rs
Labels: D5-breaks-api, crcl-runtime, D8 - migration

#1031 Add EnsureOpsAssign traits
  libs/traits/src/lib.rs
Labels: D0-ready, P2-nice-to-have, I8-enhancement

#1034 Basic EnsureOps support for FixedPoint and PerThing types
  libs/traits/src/lib.rs
  libs/traits/src/ops.rs
Labels: D0-ready, P2-nice-to-have, I8-enhancement, I6-refactoring

#1038 Ensure Ops extended
  libs/traits/src/ops.rs
Labels: Q1-easy, D0-ready, P2-nice-to-have, I8-enhancement

#1036 Rewards trait
  Cargo.lock
  flake.nix
  libs/traits/Cargo.toml
  libs/traits/src/lib.rs
  libs/traits/src/rewards.rs
Labels: D0-ready, Q3-medium, P7-asap, I8-enhancement, crcl-protocol

#944 Rewards: pallet-rewards implementation
  Cargo.lock
  Cargo.toml
  README.md
  flake.nix
  libs/traits/src/rewards.rs
  pallets/rewards/Cargo.toml
  pallets/rewards/src/lib.rs
  pallets/rewards/src/mock.rs
  pallets/rewards/src/tests.rs
  pallets/rewards/src/types.rs
Labels: I4-tests, Q5-hard, P7-asap, I8-enhancement, crcl-protocol, dependencies

#1050 Fix: Remove allowance of multi-residual tranches in low level api
  pallets/pools/src/lib.rs
  pallets/pools/src/tests.rs
  pallets/pools/src/tranche.rs
Labels: D0-ready, crcl-runtime, crcl-protocol, crcl-cross-chain

#1058 Support for reward domains as currency prefixes
  pallets/liquidity-rewards/src/lib.rs
  pallets/liquidity-rewards/src/mock.rs
  pallets/liquidity-rewards/src/tests.rs
  pallets/liquidity-rewards/src/weights.rs
  pallets/rewards/src/lib.rs
  pallets/rewards/src/mock.rs
  pallets/rewards/src/tests.rs
  runtime/development/src/lib.rs
Labels: Q1-easy, P2-nice-to-have, I8-enhancement, crcl-protocol

#1045 Pallet liquidity rewards impl
  Cargo.lock
  Cargo.toml
  README.md
  flake.nix
  libs/traits/Cargo.toml
  libs/traits/src/rewards.rs
  libs/types/src/tokens.rs
  pallets/liquidity-rewards/Cargo.toml
  pallets/liquidity-rewards/src/benchmarking.rs
  pallets/liquidity-rewards/src/lib.rs
  pallets/liquidity-rewards/src/mock.rs
  pallets/liquidity-rewards/src/tests.rs
  pallets/liquidity-rewards/src/weights.rs
  pallets/rewards/src/lib.rs
  pallets/rewards/src/mock.rs
  pallets/rewards/src/tests.rs
  pallets/rewards/src/types.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
Labels: I5-documentation, Q3-medium, I4-tests, P5-soon, D2-notify, I8-enhancement, crcl-protocol

#995 Pallet-Investments: Integration into pallet-pools
  Cargo.lock
  Cargo.toml
  flake.nix
  libs/primitives/Cargo.toml
  libs/primitives/src/lib.rs
  libs/test-utils/Cargo.toml
  libs/test-utils/src/lib.rs
  libs/test-utils/src/mocks/accountant.rs
  libs/test-utils/src/mocks/mod.rs
  libs/test-utils/src/mocks/nav.rs
  libs/test-utils/src/mocks/order_manager.rs
  libs/test-utils/src/mocks/orml_asset_registry.rs
  libs/traits/Cargo.toml
  libs/traits/src/lib.rs
  libs/types/Cargo.toml
  libs/types/src/lib.rs
  libs/types/src/tokens.rs
  pallets/bridge/Cargo.toml
  pallets/investments/Cargo.toml
  pallets/investments/src/lib.rs
  pallets/investments/src/mock.rs
  pallets/investments/src/tests.rs
  pallets/loans/Cargo.toml
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/mock.rs
  pallets/loans/src/test_utils.rs
  pallets/loans/src/tests.rs
  pallets/pools/Cargo.toml
  pallets/pools/src/benchmarking.rs
  pallets/pools/src/impls.rs
  pallets/pools/src/lib.rs
  pallets/pools/src/migrations/mod.rs
  pallets/pools/src/mock.rs
  pallets/pools/src/solution.rs
  pallets/pools/src/tests/mod.rs
  pallets/pools/src/tranche.rs
  pallets/pools/src/weights.rs
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/weights/pallet_pools.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/weights/pallet_pools.rs
Labels: D7-essential, D5-breaks-api, D9-needsaudit, crcl-runtime, D8 - migration

#1060 Minor rewards fixes/improvements
  pallets/liquidity-rewards/src/lib.rs
  pallets/rewards/src/lib.rs
  pallets/rewards/src/tests.rs
Labels: I2-bug, Q0-trivial, P2-nice-to-have, crcl-protocol
