Repository centrifuge/centrifuge-chain, pull requests merged in 2022-09, with the labels that each got.

#947 Add TrancheMetadata
  Cargo.lock
  flake.nix
  libs/common-types/Cargo.toml
  libs/common-types/src/impls.rs
  libs/common-types/src/lib.rs
  pallets/loans/Cargo.toml
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/mock.rs
  pallets/loans/src/test_utils.rs
  pallets/pools/Cargo.toml
  pallets/pools/src/benchmarking.rs
  pallets/pools/src/lib.rs
  pallets/pools/src/mock.rs
  pallets/pools/src/tests.rs
  pallets/pools/src/tranche.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/impls.rs
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/src/pools/env.rs
  runtime/integration-tests/src/pools/pool_starts.rs
  runtime/integration-tests/src/pools/utils/genesis.rs
  runtime/integration-tests/src/pools/utils/pools.rs
  runtime/integration-tests/src/xcm/kusama/restricted_calls.rs
  runtime/integration-tests/src/xcm/kusama/tests/asset_registry.rs
  runtime/integration-tests/src/xcm/kusama/tests/currency_id_convert.rs
  runtime/integration-tests/src/xcm/kusama/tests/transfers.rs
  runtime/integration-tests/src/xcm/polkadot/tests/asset_registry.rs
  runtime/integration-tests/src/xcm/polkadot/tests/currency_id_convert.rs
  runtime/integration-tests/src/xcm/polkadot/tests/mod.rs
  runtime/integration-tests/src/xcm/polkadot/tests/restricted_calls.rs
  runtime/integration-tests/src/xcm/polkadot/tests/transfers.rs
Labels: D5-breaks-api, crcl-runtime, D8 - migration

#962 Adding templates for PRs and Issues
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Q0-trivial, crcl-runtime, crcl-protocol

#978 Revert "Revert "Pallet bridge using new pallet fees (#933)" (#963)"
  Cargo.lock
  flake.nix
  libs/primitives/src/lib.rs
  libs/traits/src/lib.rs
  pallets/bridge/Cargo.toml
  pallets/bridge/src/lib.rs
  pallets/bridge/src/mock.rs
  pallets/bridge/src/tests.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
Labels: Q3-medium, I8-enhancement, D5-breaks-api, crcl-protocol

#987 Fix escalation of pool admin rights on currency roles
  runtime/altair/src/lib.rs
  runtime/development/src/lib.rs
Labels: D0-ready

#984 pallet-nft using pallet-fees
  Cargo.lock
  flake.nix
  libs/primitives/src/lib.rs
  pallets/bridge-mapping/Cargo.toml
  pallets/bridge-mapping/src/lib.rs
  pallets/bridge-mapping/src/mock.rs
  pallets/nft/src/lib.rs
  pallets/nft/src/mock.rs
  pallets/nft/src/tests.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
Labels: Q3-medium, P5-soon, I8-enhancement, crcl-protocol, D8 - migration

#990 Pallet-loans: replace Vec storage by BoundedVec
  pallets/loans/src/functions.rs
  pallets/loans/src/lib.rs
Labels: Q0-trivial, P2-nice-to-have, D2-notify

#985 pallet-investments - Tests and Fixes
  Cargo.lock
  flake.nix
  libs/primitives/src/lib.rs
  libs/traits/Cargo.toml
  libs/traits/src/lib.rs
  libs/traits/src/mocks/accountant.rs
  libs/traits/src/mocks/mod.rs
  libs/traits/src/mocks/orml_asset_registry.rs
  libs/types/src/lib.rs
  pallets/investments/Cargo.toml
  pallets/investments/src/lib.rs
  pallets/investments/src/mock.rs
  pallets/investments/src/tests.rs
  pallets/investments/src/weights.rs
  pallets/loans/src/mock.rs
  pallets/pools/src/mock.rs
Labels: D0-ready, crcl-runtime

#979 Pallet-pools: replace Vec storage by BoundedVec
  pallets/loans/src/mock.rs
  pallets/pools/src/benchmarking.rs
  pallets/pools/src/lib.rs
  pallets/pools/src/mock.rs
  runtime/altair/src/lib.rs
  runtime/development/src/lib.rs
Labels: Q1-easy, I7-optimisation, P2-nice-to-have, D2-notify, crcl-runtime

#989 Bump srtool build to Rust 1.62
  .github/workflows/build-matrix.json
  ci/script.sh
Labels: D0-ready, crcl-runtime, crcl-protocol, crcl-cross-chain

#994 Fix - remove dependencies to external `node_primitives`
  Cargo.lock
  flake.nix
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
Labels: D0-ready, crcl-runtime, crcl-protocol

#991 remove pallet-bridge-mapping
  Cargo.lock
  Cargo.toml
  README.md
  flake.nix
  pallets/bridge-mapping/Cargo.toml
  pallets/bridge-mapping/src/lib.rs
  pallets/bridge-mapping/src/mock.rs
  pallets/bridge-mapping/src/tests.rs
  pallets/bridge-mapping/src/weights.rs
Labels: Q0-trivial, D0-ready, P0-someday-maybe, I6-refactoring, crcl-cross-chain

#1008 Utility: add ensure_op trait methods to simplify overflow errors.
  libs/traits/src/lib.rs
Labels: Q0-trivial, D0-ready, I7-optimisation, P2-nice-to-have, P0-someday-maybe

#1009 Pallet-Permissions: Trigger Events Consistently
  pallets/permissions/src/lib.rs
Labels: D0-ready, crcl-runtime, crcl-protocol, crcl-cross-chain
