Repository centrifuge/centrifuge-chain, pull requests merged in 2022-12, with the labels that each got.

#1126 Adding registry to Altair
  Cargo.lock
  flake.nix
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/weights/mod.rs
  runtime/altair/src/weights/pallet_pool_registry.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
Labels: D0-ready

#1129 Fixed liquidity-reward benchmarks
  pallets/liquidity-rewards/src/benchmarking.rs
Labels: D2-notify, crcl-protocol

#1133 Fix loans benches
  Cargo.lock
  Cargo.toml
  flake.nix
  pallets/loans/Cargo.toml
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/mock.rs
  pallets/loans/src/test_utils.rs
Labels: D0-ready

#1119 Rewards: added gap mechanism
  pallets/rewards/README.md
  pallets/rewards/deferred_rewards_example.py
  pallets/rewards/gap_rewards_example.py
  pallets/rewards/src/lib.rs
  pallets/rewards/src/mechanism.rs
  pallets/rewards/src/mechanism/base.rs
  pallets/rewards/src/mechanism/deferred.rs
  pallets/rewards/src/mechanism/gap.rs
  pallets/rewards/src/mock.rs
  pallets/rewards/src/tests.rs
  pallets/rewards/src/tests/common.rs
  pallets/rewards/src/tests/currency_movement.rs
Labels: D5-breaks-api, crcl-protocol

#1141 Rewards: Implement distribution to groups with no stake
  libs/traits/src/rewards.rs
  pallets/liquidity-rewards/src/benchmarking.rs
  pallets/liquidity-rewards/src/tests.rs
  pallets/rewards/src/lib.rs
  pallets/rewards/src/mechanism.rs
  pallets/rewards/src/mechanism/base.rs
  pallets/rewards/src/mechanism/deferred.rs
  pallets/rewards/src/mechanism/gap.rs
Labels: D2-notify, crcl-protocol

#1136 Adding Codeowners
  .github/CODEOWNERS
Labels: D0-ready, crcl-runtime, crcl-protocol, crcl-cross-chain

#1149 Fix individual compilation issue
  libs/primitives/Cargo.toml
Labels: D0-ready

#1150 Rewards: All-in test. Fix gap movement
  .github/workflows/benchmark.yml
  .github/workflows/docker.yml
  .github/workflows/docs.yml
  pallets/rewards/src/mechanism/gap.rs
  pallets/rewards/src/tests.rs
  pallets/rewards/src/tests/common.rs
  pallets/rewards/src/tests/currency_movement.rs
Labels: D2-notify, crcl-protocol
