Repository centrifuge/centrifuge-chain, pull requests merged in 2022-06, with the labels that each got.

#823 Fix next loan ID being per pool rather than global
  pallets/loans/src/functions.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests.rs
Labels: I2-bug, crcl-runtime

#847 deps: Run `cargo update`
  Cargo.lock
Labels: dependencies

#852 Rename risk admins to loan admins
  libs/common-types/src/lib.rs
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/mock.rs
  pallets/loans/src/tests.rs
  runtime/integration-tests/src/pools/utils/pools.rs
Labels: crcl-runtime
