Repository centrifuge/centrifuge-chain, pull requests merged in 2022-03, with the labels that each got.

#686 Cap number of roles per location in permissions pallet
  pallets/loans/src/mock.rs
  pallets/permissions/src/lib.rs
  pallets/permissions/src/mock.rs
  pallets/permissions/src/tests.rs
  pallets/pools/src/mock.rs
  runtime/development/src/lib.rs
Labels: crcl-runtime

#620 Pool Refactoring - Main PR
  Cargo.lock
  README.md
  libs/common-traits/src/lib.rs
  libs/common-types/src/tokens.rs
  libs/proofs/Cargo.toml
  pallets/loans/src/test_utils.rs
  pallets/loans/src/tests.rs
  pallets/permissions/src/lib.rs
  pallets/pools/Cargo.toml
  pallets/pools/src/benchmarking.rs
  pallets/pools/src/lib.rs
  pallets/pools/src/mock.rs
  pallets/pools/src/solution.rs
  pallets/pools/src/tests.rs
  pallets/pools/src/tranche.rs
  pallets/pools/src/weights.rs
  runtime/common/src/impls.rs
Labels: D2-notify

#693 Rename permission extrinsic names
  libs/common-traits/src/lib.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/mock.rs
  pallets/loans/src/test_utils.rs
  pallets/loans/src/tests.rs
  pallets/permissions/src/benchmarking.rs
  pallets/permissions/src/lib.rs
  pallets/permissions/src/mock.rs
  pallets/permissions/src/tests.rs
  pallets/permissions/src/weights.rs
  pallets/pools/src/benchmarking.rs
  pallets/pools/src/lib.rs
  pallets/pools/src/mock.rs
  pallets/pools/src/tests.rs
  pallets/restricted-tokens/src/benchmarking.rs
  runtime/development/src/lib.rs
  runtime/development/src/weights/pallet_permissions.rs
Labels: crcl-runtime

#698 Move back to `shaunxw/xcm-simulator`
  Cargo.lock
  runtime/integration-tests/Cargo.toml
Labels: dependencies

#731 Pools improvements
  pallets/pools/src/benchmarking.rs
  pallets/pools/src/lib.rs
  pallets/pools/src/mock.rs
  pallets/pools/src/tests.rs
Labels: crcl-runtime

#733 `Investor` and `Borrower` proxy types
  runtime/development/src/lib.rs
Labels: I8-enhancement, crcl-runtime

#738 fix: pricing active but non borrowed against loans should be possible
  pallets/loans/src/functions.rs
  pallets/loans/src/tests.rs
Labels: crcl-runtime
