Repository centrifuge/centrifuge-chain, pull requests merged in 2022-11, with the labels that each got.

#861 Connectors POC
  Cargo.lock
  Cargo.toml
  flake.nix
  libs/traits/src/lib.rs
  pallets/connectors/Cargo.toml
  pallets/connectors/src/contract.rs
  pallets/connectors/src/lib.rs
  pallets/connectors/src/message.rs
  pallets/connectors/src/routers.rs
  pallets/connectors/src/weights.rs
  runtime/altair/src/xcm.rs
  runtime/centrifuge/src/xcm.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/xcm.rs
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/src/xcm/development/mod.rs
  runtime/integration-tests/src/xcm/development/setup.rs
  runtime/integration-tests/src/xcm/development/test_net.rs
  runtime/integration-tests/src/xcm/development/tests/connectors.rs
  runtime/integration-tests/src/xcm/development/tests/mod.rs
  runtime/integration-tests/src/xcm/mod.rs
Labels: crcl-cross-chain

#1053 Pallet-Pools: Rename to `PoolSystem`
  Cargo.lock
  Cargo.toml
  README.md
  flake.nix
  libs/types/src/impls.rs
  pallets/connectors/Cargo.toml
  pallets/loans/Cargo.toml
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/mock.rs
  pallets/loans/src/test_utils.rs
  pallets/loans/src/tests.rs
  pallets/pool-system/Cargo.toml
  pallets/pool-system/src/benchmarking.rs
  pallets/pool-system/src/impls.rs
  pallets/pool-system/src/lib.rs
  pallets/pool-system/src/migrations/mod.rs
  pallets/pool-system/src/mock.rs
  pallets/pool-system/src/solution.rs
  pallets/pool-system/src/tests/mod.rs
  pallets/pool-system/src/tranche.rs
  pallets/pool-system/src/weights.rs
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/weights/mod.rs
  runtime/altair/src/weights/pallet_pool_system.rs
  runtime/common/Cargo.toml
  runtime/common/src/apis/pools.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/weights/mod.rs
  runtime/development/src/weights/pallet_pool_system.rs
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/src/pools/pool_starts.rs
  runtime/integration-tests/src/pools/utils/env.rs
  runtime/integration-tests/src/pools/utils/pools.rs
  runtime/integration-tests/src/xcm/development/tests/connectors.rs
  src/rpc/pools.rs
Labels: D5-breaks-api, crcl-runtime

#1064 Ensure streamlined hashing
  libs/primitives/src/lib.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
Labels: D0-ready

#1061 pallet-rewards: Support different reward mechanisms
  libs/traits/src/rewards.rs
  pallets/rewards/src/lib.rs
  pallets/rewards/src/mechanism.rs
  pallets/rewards/src/mechanism/base.rs
  pallets/rewards/src/mechanism/base_with_currency_movement.rs
  pallets/rewards/src/mechanism/deferred.rs
  pallets/rewards/src/mock.rs
  pallets/rewards/src/tests.rs
  pallets/rewards/src/tests/claiming.rs
  pallets/rewards/src/tests/common.rs
  pallets/rewards/src/types.rs
  runtime/development/src/lib.rs
Labels: P7-asap, I6-refactoring, crcl-protocol

#1079 Rewards: deferred mechanism implementation
  pallets/rewards/src/lib.rs
  pallets/rewards/src/mechanism.rs
  pallets/rewards/src/mechanism/base.rs
  pallets/rewards/src/mechanism/base_with_currency_movement.rs
  pallets/rewards/src/mechanism/deferred.rs
  pallets/rewards/src/mock.rs
  pallets/rewards/src/tests.rs
  pallets/rewards/src/tests/claiming.rs
  pallets/rewards/src/tests/common.rs
Labels: Q3-medium, P7-asap, I8-enhancement, crcl-protocol

#1084 Rewards: Avoid first epoch event with zero duration
  pallets/liquidity-rewards/src/lib.rs
  pallets/liquidity-rewards/src/mock.rs
  runtime/development/src/lib.rs
Labels: I2-bug, Q0-trivial, D0-ready, P5-soon, crcl-protocol

#1094 Rewards: Add `pallet-rewards` documentation
  pallets/rewards/README.md
  pallets/rewards/deferred_python_example.py
  pallets/rewards/src/lib.rs
Labels: D0-ready, crcl-protocol

#1100 Rewards: documentation fixes
  pallets/rewards/README.md
Labels: D0-ready, crcl-protocol

#1103 Rewards: Fix for deferred mechanism
  pallets/rewards/deferred_python_example.py
  pallets/rewards/src/mechanism/deferred.rs
Labels: D0-ready, crcl-protocol
