Repository centrifuge/centrifuge-chain, pull requests merged in 2023-05, with the labels that each got.

#1324 `pallet-collection-data-feed` implementation
  Cargo.lock
  Cargo.toml
  libs/mocks/src/data.rs
  libs/mocks/src/lib.rs
  libs/traits/src/data.rs
  libs/traits/src/lib.rs
  pallets/collection-data-feed/Cargo.toml
  pallets/collection-data-feed/src/lib.rs
  pallets/collection-data-feed/src/mock.rs
  pallets/collection-data-feed/src/tests.rs
Labels: D0-ready, crcl-protocol

#1292 feat: Connectors v2 message PoC
  libs/primitives/src/lib.rs
  libs/types/src/tokens.rs
  pallets/connectors/src/lib.rs
  pallets/connectors/src/message.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/xcm/development/tests/connectors.rs
Labels: I8-enhancement, D5-breaks-api, I6-refactoring, crcl-cross-chain

#1335 Mock-builder: add support for custom lifetimes
  libs/mock-builder/src/lib.rs
  libs/mock-builder/src/location.rs
  libs/mock-builder/src/storage.rs
  libs/mock-builder/src/util.rs
  libs/mock-builder/tests/pallet.rs
  libs/mocks/src/data.rs
  libs/mocks/src/fees.rs
  libs/mocks/src/pools.rs
  libs/mocks/src/rewards.rs
Labels: D2-notify, crcl-protocol

#1323 Add transfer allowlist benchmarks
  Cargo.lock
  libs/types/src/locations.rs
  pallets/transfer-allowlist/Cargo.toml
  pallets/transfer-allowlist/src/benchmarking.rs
  pallets/transfer-allowlist/src/lib.rs
  pallets/transfer-allowlist/src/mock.rs
  pallets/transfer-allowlist/src/tests.rs
  pallets/transfer-allowlist/src/weights.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/weights/pallet_transfer_allowlist.rs
Labels: D0-ready

#1344 refactor: remove rewards domain concept
  Cargo.lock
  pallets/block-rewards/src/benchmarking.rs
  pallets/block-rewards/src/lib.rs
  pallets/block-rewards/src/migrations.rs
  pallets/block-rewards/src/mock.rs
  pallets/block-rewards/src/tests.rs
  pallets/liquidity-rewards/src/lib.rs
  pallets/liquidity-rewards/src/mock.rs
  pallets/liquidity-rewards/src/tests.rs
  pallets/rewards/src/lib.rs
  pallets/rewards/src/mock.rs
  pallets/rewards/src/tests.rs
  pallets/rewards/src/tests/command_based.rs
  pallets/rewards/src/tests/common.rs
  pallets/rewards/src/tests/currency_movement.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/apis/rewards.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/rewards/block/invariants.rs
  runtime/integration-tests/src/rewards/block/session_advances.rs
  runtime/integration-tests/src/runtime_apis/rewards.rs
  src/rpc/rewards.rs
Labels: Q1-easy, P7-asap, D2-notify, I6-refactoring, I11-cleaning

#1346 Mocks: Use mock test utility without dependencies
  Cargo.lock
  libs/mocks/Cargo.toml
  libs/mocks/src/lib.rs
  libs/traits/Cargo.toml
Labels: Q1-easy, D0-ready, crcl-protocol, I11-cleaning

#1342 feat: add block rewards to altair and centrifuge runtimes
  Cargo.lock
  libs/types/src/ids.rs
  pallets/block-rewards/src/benchmarking.rs
  pallets/block-rewards/src/lib.rs
  pallets/block-rewards/src/migrations.rs
  pallets/block-rewards/src/mock.rs
  pallets/block-rewards/src/tests.rs
  pallets/liquidity-rewards/src/lib.rs
  pallets/liquidity-rewards/src/mock.rs
  pallets/liquidity-rewards/src/tests.rs
  pallets/rewards/Cargo.toml
  pallets/rewards/src/lib.rs
  pallets/rewards/src/migrations/new_instance.rs
  pallets/rewards/src/mock.rs
  pallets/rewards/src/tests.rs
  pallets/rewards/src/tests/command_based.rs
  pallets/rewards/src/tests/common.rs
  pallets/rewards/src/tests/currency_movement.rs
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/migrations.rs
  runtime/altair/src/weights/mod.rs
  runtime/altair/src/weights/pallet_block_rewards.rs
  runtime/altair/src/weights/pallet_collator_selection.rs
  runtime/altair/src/weights/pallet_session.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/centrifuge/src/weights/mod.rs
  runtime/centrifuge/src/weights/pallet_block_rewards.rs
  runtime/centrifuge/src/weights/pallet_session.rs
  runtime/common/Cargo.toml
  runtime/common/src/apis/rewards.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/rewards/block/env.rs
  runtime/integration-tests/src/rewards/block/invariants.rs
  runtime/integration-tests/src/rewards/block/session_advances.rs
  runtime/integration-tests/src/runtime_apis/rewards.rs
  src/chain_spec.rs
  src/rpc/rewards.rs
Labels: I9-release, P7-asap, D8-migration

#1348 Restricted-tokens: Sync call indicies with orml
  pallets/restricted-tokens/src/lib.rs
Labels: D5-breaks-api

#1351 CollectionDataFeed: Minor changes
  libs/mocks/src/data.rs
  libs/traits/src/data.rs
  pallets/collection-data-feed/Cargo.toml
  pallets/collection-data-feed/src/lib.rs
  pallets/collection-data-feed/src/mock.rs
  pallets/collection-data-feed/src/tests.rs
Labels: Q1-easy, P7-asap, I6-refactoring, crcl-protocol

#1362 mock-builder: Main documentation
  .github/workflows/docs.yml
  libs/mock-builder/src/lib.rs
Labels: I5-documentation, D0-ready, P7-asap

#1308 Fix: Local runtime upgrade scripts
  scripts/js/onboard/package.json
  scripts/js/onboard/yarn.lock
  scripts/js/upgrade/index.js
  scripts/js/upgrade/package.json
  scripts/js/upgrade/yarn.lock
Labels: D0-ready, dependencies

#1366 Data collector: renamed and instanciable
  Cargo.lock
  Cargo.toml
  pallets/data-collector/Cargo.toml
  pallets/data-collector/src/lib.rs
  pallets/data-collector/src/mock.rs
  pallets/data-collector/src/tests.rs
Labels: Q1-easy, D0-ready, P7-asap, I6-refactoring, crcl-protocol

#1367 Loans: LoanId out from ActiveLoan
  pallets/loans-ref/src/lib.rs
  pallets/loans-ref/src/loan.rs
  pallets/loans-ref/src/tests.rs
Labels: Q1-easy, P0-someday-maybe, I6-refactoring

#1368 Loans: Add unchecked amount support
  pallets/loans-ref/src/benchmarking.rs
  pallets/loans-ref/src/lib.rs
  pallets/loans-ref/src/loan.rs
  pallets/loans-ref/src/tests.rs
  runtime/integration-tests/src/utils/loans.rs
Labels: Q1-easy, P9-drop-everything, I8-enhancement, D5-breaks-api, crcl-protocol

#1373 Loans: remove old pallet-loans
  README.md
  pallets/loans/Cargo.toml
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/functions.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/loan_type.rs
  pallets/loans/src/math.rs
  pallets/loans/src/mock.rs
  pallets/loans/src/test_utils.rs
  pallets/loans/src/tests.rs
  pallets/loans/src/types.rs
  pallets/loans/src/weights.rs
Labels: D0-ready

#1372 Loans: Support for benchmarking prices
  libs/mocks/src/data.rs
  libs/traits/src/data.rs
  pallets/data-collector/Cargo.toml
  pallets/data-collector/src/lib.rs
  pallets/loans-ref/src/benchmarking.rs
  pallets/loans-ref/src/mock.rs
  pallets/loans-ref/src/util.rs
Labels: D0-ready, Q3-medium, P5-soon, I8-enhancement
