Repository centrifuge/centrifuge-chain, pull requests merged in 2023-06, with the labels that each got.

#1387 Loans: Change price type from `Balance` to `Rate`
  pallets/loans-ref/src/benchmarking.rs
  pallets/loans-ref/src/lib.rs
  pallets/loans-ref/src/mock.rs
  pallets/loans-ref/src/pricing/external.rs
  pallets/loans-ref/src/tests.rs
  pallets/loans-ref/src/util.rs
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
Labels: Q1-easy, D0-ready, P5-soon, I6-refactoring, crcl-protocol

#1389 Rename `MemberListAdmin` to `InvestorAdmin`
  libs/types/src/permissions.rs
  pallets/connectors/src/lib.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/utils/pools.rs
  runtime/integration-tests/src/xcm/development/tests/connectors.rs
Labels: D0-ready

#1384 Loans: `ChangeGuard` trait and loans modifications
  Cargo.lock
  libs/mocks/src/change_guard.rs
  libs/mocks/src/lib.rs
  libs/traits/src/changes.rs
  libs/traits/src/lib.rs
  pallets/loans-ref/src/lib.rs
  pallets/loans-ref/src/loan.rs
  pallets/loans-ref/src/mock.rs
  pallets/loans-ref/src/pricing.rs
  pallets/loans-ref/src/pricing/internal.rs
  pallets/loans-ref/src/tests.rs
  pallets/loans-ref/src/types/mod.rs
  pallets/loans-ref/src/types/policy.rs
  pallets/loans-ref/src/util.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
Labels: D0-ready, Q3-medium, P5-soon, crcl-protocol

#1394 Loans: module reorganization
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/entities/pricing/internal.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/migrations/v1.rs
  pallets/loans/src/tests.rs
  pallets/loans/src/tests/borrow_loan.rs
  pallets/loans/src/tests/close_loan.rs
  pallets/loans/src/tests/create_loan.rs
  pallets/loans/src/tests/mock.rs
  pallets/loans/src/tests/mod.rs
  pallets/loans/src/tests/mutate_loan.rs
  pallets/loans/src/tests/policy.rs
  pallets/loans/src/tests/portfolio_valuation.rs
  pallets/loans/src/tests/repay_loan.rs
  pallets/loans/src/tests/util.rs
  pallets/loans/src/tests/write_off_loan.rs
  runtime/integration-tests/src/utils/loans.rs
Labels: Q0-trivial, I4-tests, P5-soon, I6-refactoring, crcl-protocol

#1410 fix: order id storage in do_collect_redeem
  pallets/investments/src/lib.rs
Labels: I2-bug, D0-ready

#1396 ChangeGuard pool-system implementation
  Cargo.lock
  libs/primitives/src/lib.rs
  libs/types/src/epoch.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/mock.rs
  pallets/loans/src/tests/mod.rs
  pallets/loans/src/util.rs
  pallets/pool-registry/src/mock.rs
  pallets/pool-system/Cargo.toml
  pallets/pool-system/src/impls.rs
  pallets/pool-system/src/lib.rs
  pallets/pool-system/src/mock.rs
  pallets/pool-system/src/pool_types.rs
  pallets/pool-system/src/tests/mod.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
Labels: Q3-medium, I8-enhancement, crcl-protocol

#1402 Oracles: add to altair and centrifuge runtimes
  Cargo.lock
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
Labels: D2-notify

#1414 Use substrate `ensure_ops` implementation
  libs/traits/src/lib.rs
  libs/traits/src/ops.rs
  libs/traits/src/rewards.rs
  pallets/block-rewards/src/lib.rs
  pallets/interest-accrual/src/lib.rs
  pallets/liquidity-rewards/src/lib.rs
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/entities/pricing/internal.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/types/portfolio.rs
  pallets/loans/src/types/valuation.rs
  pallets/pool-system/src/lib.rs
  pallets/pool-system/src/solution.rs
  pallets/pool-system/src/tranches.rs
  pallets/rewards/src/mechanism/base.rs
  pallets/rewards/src/mechanism/deferred.rs
  pallets/rewards/src/mechanism/gap.rs
  pallets/transfer-allowlist/src/lib.rs
  runtime/integration-tests/src/utils/loans.rs
Labels: Q1-easy, D0-ready

#1420 Mock builder: Support nested mock calls
  libs/mock-builder/src/lib.rs
  libs/mock-builder/src/storage.rs
  libs/mock-builder/tests/pallet.rs
Labels: P7-asap, I8-enhancement, crcl-protocol

#1419 Loans: mutation weights calculated by benchmarks
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/weights.rs
  pallets/pool-system/src/impls.rs
  pallets/pool-system/src/tests/mod.rs
  runtime/altair/src/weights/pallet_loans.rs
  runtime/centrifuge/src/weights/pallet_loans.rs
  runtime/development/src/weights/pallet_loans.rs
Labels: D0-ready

#1428 Loans: unlimit external pricing borrows
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/tests/borrow_loan.rs
  pallets/loans/src/tests/create_loan.rs
  pallets/loans/src/tests/mod.rs
  pallets/loans/src/tests/util.rs
Labels: P7-asap, I8-enhancement, D5-breaks-api

#1425 Rewards: liquidity using gap & remove pallet-timestamp dependency
  Cargo.lock
  libs/mocks/src/lib.rs
  libs/mocks/src/time.rs
  pallets/liquidity-rewards/Cargo.toml
  pallets/liquidity-rewards/src/benchmarking.rs
  pallets/liquidity-rewards/src/mock.rs
  pallets/liquidity-rewards/src/tests.rs
  pallets/rewards/src/mechanism/gap.rs
  runtime/common/src/apis/rewards.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/runtime_apis/rewards.rs
Labels: D5-breaks-api
