Repository centrifuge/centrifuge-chain, pull requests merged in 2023-08, with the labels that each got.

#1463 Update ProxyType for runtimes
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
Labels: I9-release, P7-asap, D2-notify, crcl-runtime

#1471 Loans: Quantity as fixed point with 18 decimals
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/borrow_loan.rs
  pallets/loans/src/tests/create_loan.rs
  pallets/loans/src/tests/mock.rs
  pallets/loans/src/tests/repay_loan.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
Labels: Q1-easy, I3-annoyance, P7-asap, D2-notify, crcl-protocol, D8-migration

#1482 Loans: add outstanding principal & interest to runtime API
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/entities/pricing/internal.rs
Labels: Q1-easy, I3-annoyance, P7-asap, D5-breaks-api

#1474 Oracle: USD pricing for multiple stables
  Cargo.lock
  libs/mocks/src/data.rs
  libs/primitives/Cargo.toml
  libs/primitives/src/conversion.rs
  libs/primitives/src/lib.rs
  libs/traits/src/data.rs
  libs/types/src/fixed_point.rs
  pallets/data-collector/src/lib.rs
  pallets/data-collector/src/mock.rs
  pallets/data-collector/src/tests.rs
  pallets/loans/docs/types.md
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/borrow_loan.rs
  pallets/loans/src/tests/create_loan.rs
  pallets/loans/src/tests/mock.rs
  pallets/loans/src/tests/policy.rs
  pallets/loans/src/tests/portfolio_valuation.rs
  pallets/loans/src/tests/repay_loan.rs
  pallets/loans/src/tests/util.rs
  pallets/loans/src/tests/write_off_loan.rs
  pallets/loans/src/util.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/lib.rs
  runtime/common/src/oracle.rs
  runtime/development/src/lib.rs
Labels: Q5-hard, P5-soon, I8-enhancement, D5-breaks-api, D8-migration

#1484 Feature/precompile v3
  Cargo.lock
  Cargo.toml
  pallets/connectors-gateway/axelar-gateway-precompile/Cargo.toml
  pallets/connectors-gateway/axelar-gateway-precompile/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/evm/precompile.rs
  runtime/development/Cargo.toml
  runtime/development/src/evm.rs
  runtime/development/src/lib.rs
Labels: D0-ready

#1498 fix: identifying algol chain correctly
  src/command.rs
Labels: D0-ready

#1487 Loans: add slippage for external pricing
  pallets/loans/docs/types.md
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/borrow_loan.rs
  pallets/loans/src/tests/mock.rs
  pallets/loans/src/tests/repay_loan.rs
  pallets/loans/src/tests/util.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
Labels: Q3-medium, I8-enhancement, D8-migration

#1500 Fix missing cargo features
  libs/mocks/Cargo.toml
  pallets/claims/Cargo.toml
  pallets/ethereum-transaction/Cargo.toml
  pallets/liquidity-pools-gateway/Cargo.toml
  pallets/liquidity-pools-gateway/axelar-gateway-precompile/Cargo.toml
  pallets/liquidity-pools-gateway/routers/Cargo.toml
  pallets/order-book/Cargo.toml
  runtime/altair/Cargo.toml
  runtime/centrifuge/Cargo.toml
  runtime/common/Cargo.toml
  runtime/development/Cargo.toml
  runtime/integration-tests/Cargo.toml
Labels: D0-ready

#1504 Loans: close with repays amount
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/tests/borrow_loan.rs
  pallets/loans/src/tests/repay_loan.rs
Labels: Q1-easy, P7-asap, I6-refactoring, D8-migration

#1492 Generic nuke migrations
  Cargo.lock
  pallets/loans/Cargo.toml
  pallets/loans/src/lib.rs
  pallets/loans/src/migrations/nuke.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/migrations/nuke.rs
Labels: P5-soon, D9-needsaudit, I6-refactoring

#1347 Register pools with write-off policy
  Cargo.lock
  libs/mocks/src/lib.rs
  libs/mocks/src/write_off_policy.rs
  libs/traits/src/lib.rs
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/lib.rs
  pallets/pool-registry/Cargo.toml
  pallets/pool-registry/src/benchmarking.rs
  pallets/pool-registry/src/lib.rs
  pallets/pool-registry/src/mock.rs
  pallets/pool-registry/src/tests.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/utils/pools.rs
Labels: I8-enhancement, D5-breaks-api

#1503 Only validate Frontier logs from after the EVM was enabled.
  res/algol-spec.json
  res/catalyst-spec-raw.json
  res/catalyst-spec.json
  res/genesis/altair-genesis-spec-raw.json
  res/genesis/altair-genesis-spec.json
  res/genesis/centrifuge-genesis-spec-raw.json
  res/genesis/centrifuge-genesis-spec.json
  src/chain_spec.rs
  src/command.rs
  src/service.rs
  src/service/evm.rs
Labels: D2-notify

#1506 Add nuke migration for loans & interest-accrual
  pallets/interest-accrual/src/lib.rs
  runtime/altair/src/lib.rs
  runtime/altair/src/migrations.rs
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/development/src/lib.rs
  src/chain_spec.rs
Labels: I9-release, P5-soon, crcl-protocol, D8-migration

#1508 Rewards: Add deposit for reward account for Altair. Enable liquidity rewards for all chains based on Altair
  runtime/altair/src/lib.rs
  runtime/altair/src/migrations.rs
  src/chain_spec.rs
Labels: crcl-protocol

#1505 Remove unused imports and minor clean ups
  runtime/centrifuge/src/lib.rs
Labels: D0-ready

#1512 Use latest settlement price by default
  pallets/loans/docs/types.md
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/borrow_loan.rs
  pallets/loans/src/tests/mock.rs
  pallets/loans/src/tests/portfolio_valuation.rs
  pallets/loans/src/tests/repay_loan.rs
  pallets/loans/src/types/mod.rs
Labels: Q3-medium, P7-asap, I8-enhancement

#1518 Order book extension
  libs/traits/src/lib.rs
  pallets/crowdloan-reward/src/lib.rs
  pallets/order-book/src/benchmarking.rs
  pallets/order-book/src/lib.rs
  pallets/order-book/src/mock.rs
  pallets/order-book/src/tests.rs
  pallets/order-book/src/weights.rs
  runtime/development/src/lib.rs
  runtime/development/src/weights/pallet_order_book.rs
  scripts/tests.sh
Labels: D0-ready

#1519 LiquidityRewards: support for centrifuge runtime
  Cargo.lock
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/centrifuge/src/weights/mod.rs
  runtime/centrifuge/src/weights/pallet_liquidity_rewards.rs
  src/chain_spec.rs
Labels: Q1-easy, P7-asap, I8-enhancement, D8-migration
