Repository centrifuge/centrifuge-chain, pull requests merged in 2023-09, with the labels that each got.

#1520 Pools: use `Rate` represented as 18 decimals
  libs/mocks/src/pools.rs
  libs/traits/src/lib.rs
  pallets/investments/src/lib.rs
  pallets/liquidity-pools/src/lib.rs
  pallets/loans/src/tests/mock.rs
  pallets/pool-registry/src/lib.rs
  pallets/pool-registry/src/mock.rs
  pallets/pool-system/src/impls.rs
  pallets/pool-system/src/lib.rs
  pallets/pool-system/src/mock.rs
  pallets/pool-system/src/tests/mod.rs
  pallets/pool-system/src/tranches.rs
  runtime/altair/src/lib.rs
  runtime/altair/src/migrations.rs
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/src/migrations/nuke.rs
  runtime/development/src/lib.rs
  runtime/development/src/liquidity_pools.rs
  runtime/integration-tests/src/liquidity_pools/pallet/development/tests/liquidity_pools.rs
  runtime/integration-tests/src/liquidity_pools/pallet/development/tests/routers/axelar_evm.rs
  runtime/integration-tests/src/liquidity_pools/pallet/development/tests/routers/ethereum_xcm.rs
Labels: I3-annoyance, I9-release, P7-asap

#1534 chore: remove Centrifuge 1020 & Algol 1031 migrations
  runtime/altair/src/lib.rs
  runtime/altair/src/migrations.rs
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
Labels: D0-ready

#1536 fix: ethereum transaction pallet must forward to pallet-ethereum::transact
  Cargo.lock
  pallets/ethereum-transaction/src/lib.rs
  pallets/ethereum-transaction/src/mock.rs
  pallets/ethereum-transaction/src/tests.rs
  pallets/liquidity-pools-gateway/routers/src/lib.rs
  pallets/liquidity-pools-gateway/routers/src/mock.rs
  pallets/liquidity-pools-gateway/routers/src/routers/axelar_evm.rs
  pallets/liquidity-pools/src/lib.rs
  runtime/altair/Cargo.toml
  runtime/altair/src/evm.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/evm.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/evm.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/src/ethereum_transaction/pallet.rs
Labels: D0-ready

#1543 Fix rate type used in RuntimeAPIs for pools
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
Labels: I2-bug, Q0-trivial, P7-asap

#1546 OrderBook: Use ratio instead of rate
  pallets/order-book/src/benchmarking.rs
  pallets/order-book/src/mock.rs
  pallets/order-book/src/tests.rs
  runtime/development/src/lib.rs
Labels: Q1-easy, I3-annoyance, P7-asap

#1548 feat: encode source address correctly in gateway
  Cargo.lock
  libs/mocks/src/liquidity_pools.rs
  libs/utils/Cargo.toml
  libs/utils/src/lib.rs
  pallets/liquidity-pools-gateway/Cargo.toml
  pallets/liquidity-pools-gateway/axelar-gateway-precompile/Cargo.toml
  pallets/liquidity-pools-gateway/axelar-gateway-precompile/src/lib.rs
  pallets/liquidity-pools-gateway/routers/Cargo.toml
  pallets/liquidity-pools-gateway/src/lib.rs
  pallets/liquidity-pools-gateway/src/mock.rs
  pallets/liquidity-pools-gateway/src/tests.rs
  runtime/altair/src/lib.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/liquidity_pools.rs
  runtime/development/src/xcm.rs
  rustfmt.toml
Labels: D0-ready

#1549 chore: Algol 1033
  Cargo.lock
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/migrations.rs
Labels: D0-ready, I9-release, P7-asap

#1556 feat: enable full foreign collect flow via extrinsic
  libs/traits/src/investments.rs
  libs/types/src/investments.rs
  pallets/foreign-investments/src/errors.rs
  pallets/foreign-investments/src/impls/mod.rs
  pallets/foreign-investments/src/lib.rs
  pallets/liquidity-pools/src/hooks.rs
  pallets/liquidity-pools/src/inbound.rs
  pallets/liquidity-pools/src/lib.rs
  pallets/liquidity-pools/src/message.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/liquidity_pools/pallet/development/tests/liquidity_pools/add_allow_upgrade.rs
  runtime/integration-tests/src/liquidity_pools/pallet/development/tests/liquidity_pools/foreign_investments.rs
Labels: D0-ready, P7-asap, D5-breaks-api

#1558 feat: orderbook bench helper
  libs/mocks/src/pools.rs
  libs/traits/src/benchmarking.rs
  libs/traits/src/lib.rs
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/tests/mock.rs
  pallets/order-book/src/benchmarking.rs
  pallets/order-book/src/lib.rs
  pallets/pool-system/src/impls.rs
  pallets/pool-system/src/tests/mod.rs
Labels: D0-ready, I8-enhancement

#1561 Loans: Remove portfolio entry when removing a loan + portfolio UT
  pallets/loans/src/lib.rs
  pallets/loans/src/types/portfolio.rs
Labels: Q1-easy, I3-annoyance, D0-ready, P2-nice-to-have

#1566 centrifuge: Anemoy pool currency migration
  libs/types/src/tokens.rs
  pallets/investments/src/lib.rs
  runtime/centrifuge/src/migrations.rs
Labels: D8-migration

#1563 Investments: benchmarks
  libs/mocks/src/pools.rs
  libs/test-utils/src/mocks/accountant.rs
  pallets/investments/src/benchmarking.rs
  pallets/investments/src/lib.rs
  pallets/investments/src/mock.rs
  pallets/investments/src/tests.rs
  pallets/investments/src/weights.rs
  runtime/altair/src/lib.rs
  runtime/altair/src/weights/mod.rs
  runtime/altair/src/weights/pallet_investments.rs
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/weights/mod.rs
  runtime/centrifuge/src/weights/pallet_investments.rs
  runtime/development/src/lib.rs
Labels: I7-optimisation, P7-asap, D2-notify, crcl-protocol

#1565 feat: benchmark foreign investments worst case
  libs/traits/src/benchmarking.rs
  pallets/foreign-investments/src/impls/benchmark_utils.rs
  pallets/foreign-investments/src/impls/mod.rs
  pallets/foreign-investments/src/lib.rs
  pallets/liquidity-pools-gateway/src/lib.rs
  pallets/liquidity-pools/src/benchmarking.rs
  pallets/liquidity-pools/src/defensive_weights.rs
  pallets/liquidity-pools/src/lib.rs
  pallets/liquidity-pools/src/weights.rs
  pallets/pool-system/src/impls.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/liquidity_pools/pallet/development/tests/liquidity_pools/foreign_investments.rs
Labels: I8-enhancement

#1509 ForeignInvestments: Unitary tests & fuzzer
  Cargo.lock
  libs/mock-builder/src/lib.rs
  libs/mocks/src/currency_conversion.rs
  libs/mocks/src/investment.rs
  libs/mocks/src/lib.rs
  libs/mocks/src/status_notification.rs
  libs/mocks/src/token_swaps.rs
  libs/traits/src/investments.rs
  libs/types/src/investments.rs
  pallets/foreign-investments/Cargo.toml
  pallets/foreign-investments/src/hooks.rs
  pallets/foreign-investments/src/impls/invest.rs
  pallets/foreign-investments/src/impls/mod.rs
  pallets/foreign-investments/src/impls/redeem.rs
  pallets/foreign-investments/src/lib.rs
  pallets/foreign-investments/src/mock.rs
  pallets/foreign-investments/src/tests.rs
  pallets/foreign-investments/src/types.rs
Labels: I4-tests, P5-soon, crcl-protocol

#1569 MockBuilder: fix doc link
  libs/mock-builder/src/lib.rs
Labels: Q0-trivial, I5-documentation, P7-asap

#1570 fix: min fulfillment amount for partial fulfillment
  libs/mocks/src/token_swaps.rs
  libs/traits/src/lib.rs
  pallets/foreign-investments/src/hooks.rs
  pallets/foreign-investments/src/impls/mod.rs
  pallets/foreign-investments/src/tests.rs
  pallets/order-book/src/benchmarking.rs
  pallets/order-book/src/lib.rs
  pallets/order-book/src/mock.rs
  pallets/order-book/src/tests.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/liquidity_pools/pallet/development/tests/liquidity_pools/foreign_investments.rs
Labels: I2-bug, D0-ready, P7-asap

#1571 Investments: simplify constraints and remove InvestmentProperties trait
  libs/test-utils/src/mocks/accountant.rs
  libs/test-utils/src/mocks/order_manager.rs
  libs/traits/src/investments.rs
  libs/types/src/investments.rs
  pallets/investments/src/benchmarking.rs
  pallets/investments/src/lib.rs
  pallets/investments/src/mock.rs
  pallets/pool-registry/src/benchmarking.rs
  pallets/pool-system/src/benchmarking.rs
Labels: Q3-medium, P2-nice-to-have, I11-cleaning

#1572 fix: foreign investments bench
  pallets/foreign-investments/src/impls/benchmark_utils.rs
Labels: D0-ready, I12-ci

#1465 Loans: transfer_debt implementation
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/entities/changes.rs
  pallets/loans/src/entities/input.rs
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing.rs
  pallets/loans/src/entities/pricing/internal.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/borrow_loan.rs
  pallets/loans/src/tests/close_loan.rs
  pallets/loans/src/tests/mock.rs
  pallets/loans/src/tests/mod.rs
  pallets/loans/src/tests/mutate_loan.rs
  pallets/loans/src/tests/policy.rs
  pallets/loans/src/tests/portfolio_valuation.rs
  pallets/loans/src/tests/repay_loan.rs
  pallets/loans/src/tests/transfer_debt.rs
  pallets/loans/src/tests/util.rs
  pallets/loans/src/tests/write_off_loan.rs
  pallets/loans/src/types/mod.rs
  pallets/loans/src/util.rs
  pallets/loans/src/weights.rs
  runtime/altair/src/weights/pallet_loans.rs
  runtime/centrifuge/src/weights/pallet_loans.rs
  runtime/common/src/lib.rs
  runtime/development/src/weights/pallet_loans.rs
  runtime/integration-tests/src/utils/loans.rs
Labels: D2-notify, D5-breaks-api

#1491 Github codeowners/templates changes
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: crcl-protocol
