Repository centrifuge/centrifuge-chain, pull requests merged in 2023-04, with the labels that each got.

#1299 InterestAccrual: Unify current & previous debt methods
  libs/traits/src/lib.rs
  pallets/interest-accrual/src/lib.rs
  pallets/loans-ref/src/tests.rs
  pallets/loans-ref/src/types.rs
Labels: D0-ready, crcl-protocol

#1302 Altair Release 1026 & Development Release 1019
  Cargo.lock
  Cargo.toml
  flake.nix
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
Labels: D2-notify

#1300 Add benchmark CI job for fast checks
  .github/workflows/benchmark-check.yml
  ci/script.sh
  scripts/check_benchmarks.sh
Labels: D0-ready, crcl-protocol

#1251 Pallet transfers allowlist
  Cargo.lock
  Cargo.toml
  flake.nix
  libs/traits/src/lib.rs
  libs/types/Cargo.toml
  libs/types/src/domain_address.rs
  libs/types/src/fee_keys.rs
  libs/types/src/lib.rs
  libs/types/src/locations.rs
  pallets/connectors/src/lib.rs
  pallets/transfer-allowlist/Cargo.toml
  pallets/transfer-allowlist/src/lib.rs
  pallets/transfer-allowlist/src/mock.rs
  pallets/transfer-allowlist/src/tests.rs
  runtime/integration-tests/src/xcm/development/tests/connectors.rs
Labels: D0-ready

#1313 fix: update rococo-local to Polkadot v0.9.37
  res/rococo-local.json
Labels: D0-ready, dependencies

#1318 ci: disable docker nix build
  .github/workflows/docker-nix.yml
  ci/script.sh
Labels: D0-ready, P9-drop-everything, I12-ci

#1314 Loans: Add multiple triggers for write-off
  Cargo.lock
  pallets/loans-ref/Cargo.toml
  pallets/loans-ref/src/benchmarking.rs
  pallets/loans-ref/src/lib.rs
  pallets/loans-ref/src/migrations/nuke.rs
  pallets/loans-ref/src/migrations/v1.rs
  pallets/loans-ref/src/mock.rs
  pallets/loans-ref/src/tests.rs
  pallets/loans-ref/src/types.rs
  pallets/loans-ref/src/write_off.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
Labels: Q3-medium, P5-soon, D5-breaks-api, crcl-protocol, D8 - migration

#1321 Mock-builder with generic methods support
  libs/mock-builder/Cargo.toml
  libs/mock-builder/src/lib.rs
  libs/mock-builder/src/location.rs
  libs/mock-builder/src/storage.rs
  libs/mock-builder/tests/pallet.rs
Labels: D0-ready, P5-soon
