Repository centrifuge/centrifuge-chain, pull requests merged in 2023-11, with the labels that each got.

#1568 fix: typos
  docs/runtime-upgrade.md
  pallets/rewards/README.md
Labels: D0-ready

#1610 LiquidityPools: Add `restriction_set` field to `AddTranche` message
  pallets/liquidity-pools/src/lib.rs
  pallets/liquidity-pools/src/message.rs
Labels: P5-soon, D2-notify, I8-enhancement

#1608 feat: add InvestmentPortfolio Runtime API
  Cargo.lock
  libs/primitives/src/lib.rs
  libs/traits/src/investments.rs
  libs/types/src/fixed_point.rs
  libs/types/src/investments.rs
  pallets/investments/src/lib.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/apis/investments.rs
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/generic/cases/investments.rs
  runtime/integration-tests/src/generic/config.rs
  runtime/integration-tests/src/generic/mod.rs
  runtime/integration-tests/src/generic/utils/mod.rs
Labels: I9-release, P7-asap, D2-notify, I8-enhancement, D5-breaks-api

#1611 CI release bug fixes
  .github/workflows/build-docker.yml
  .github/workflows/build-wasm.yml
  .github/workflows/docs.yml
Labels: I2-bug, Q0-trivial, D0-ready, I12-ci, github_actions

#1615 Fix: Transfer debt
  pallets/pool-system/src/impls.rs
  pallets/pool-system/src/tests/mod.rs
  runtime/common/src/lib.rs
Labels: I3-annoyance, P7-asap, D2-notify

#1609 Runtimes workspace dependencies & cleaning
  Cargo.lock
  Cargo.toml
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/fees.rs
  runtime/common/src/lib.rs
  runtime/common/src/tests/mock.rs
  runtime/common/src/tests/mod.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/src/utils/extrinsics.rs
  scripts/runtime-weight-template.hbs
Labels: Q5-hard, I6-refactoring, dependencies, I11-cleaning

#1616 Fix: Loans adjustments
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
Labels: Q0-trivial, I3-annoyance, D0-ready, P7-asap

#1622 fix: enable rocksdb for frontier backend
  Cargo.lock
  Cargo.toml
Labels: I2-bug, P9-drop-everything

#1619 CI bug fixes - Part II
  .github/workflows/docs.yml
Labels: Q0-trivial, I12-ci, github_actions

#1624 Dockerfile review after CI changes
  .github/workflows/build-docker.yml
  docker/centrifuge-chain/Dockerfile
Labels: D0-ready, P7-asap, I12-ci

#1623 Fees API Improvement
  libs/traits/src/lib.rs
  libs/types/src/fee_keys.rs
  runtime/common/src/fees.rs
Labels: P2-nice-to-have, I6-refactoring

#1628 Docker: solve polkadot relay folder renaming and other small fixes
  .dockerignore
  .github/dependabot.yml
  .github/workflows/build-docker.yml
  docker/centrifuge-chain/Dockerfile
  docker/scripts/entrypoint.sh
Labels: Q1-easy, I3-annoyance, D0-ready, I12-ci, github_actions
