Repository centrifuge/centrifuge-chain, pull requests merged in 2023-12, with the labels that each got.

#1637 Modify `RuntimeChange` to support easily new additions
  runtime/common/src/changes.rs
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
Labels: I3-annoyance, P7-asap, I6-refactoring

#1626 fix: docker-compose
  docker/docker-compose-local-chain.yml
  docker/docker-compose-local-relay.yml
  scripts/init.sh
Labels: I2-bug, D0-ready

#1640 Fix benchmark issue in development
  runtime/common/src/changes.rs
Labels: P9-drop-everything, I1-fails

#1636 Sanity checks: re-activate Taplo
  .github/workflows/sanity-checks.yml
  Cargo.toml
  ci/run-check.sh
  libs/types/Cargo.toml
  pallets/restricted-xtokens/Cargo.toml
  runtime/centrifuge/Cargo.toml
Labels: D0-ready, P2-nice-to-have, I12-ci

#1642 fix: build docker on draft release
  .github/workflows/build-docker.yml
Labels: I9-release, P9-drop-everything, I12-ci

#1645 Split concern for pool benchmark helper
  libs/mocks/src/pools.rs
  libs/test-utils/src/mocks/accountant.rs
  libs/traits/src/benchmarking.rs
  pallets/foreign-investments/src/impls/benchmark_utils.rs
  pallets/investments/src/benchmarking.rs
  pallets/loans/src/benchmarking.rs
  pallets/pool-system/src/impls.rs
Labels: Q1-easy, P7-asap, I6-refactoring

#1646 Fix Docker workflow triggers
  .github/workflows/build-docker.yml
Labels: Q1-easy, D0-ready

#1652 Substitute mock-accountant macro by a mock builder pallet
  Cargo.lock
  libs/mocks/src/pools.rs
  libs/test-utils/src/mocks/accountant.rs
  libs/test-utils/src/mocks/authority_origin.rs
  libs/test-utils/src/mocks/mod.rs
  libs/test-utils/src/mocks/order_manager.rs
  pallets/investments/Cargo.toml
  pallets/investments/src/benchmarking.rs
  pallets/investments/src/mock.rs
  pallets/investments/src/tests.rs
Labels: P2-nice-to-have, I11-cleaning

#1653 Loans: Expand `TransferDebt` event with more info
  Cargo.lock
  pallets/loans/src/lib.rs
Labels: Q0-trivial, I3-annoyance, P5-soon, D5-breaks-api

#1657 Fix: LP accounting
  Cargo.lock
  libs/types/src/tokens.rs
  pallets/liquidity-pools/src/lib.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/src/xcm.rs
  runtime/integration-tests/src/generic/cases/liquidity_pools.rs
Labels: D8-migration

#1629 Oracle V2 implementation
  Cargo.lock
  Cargo.toml
  libs/mocks/src/change_guard.rs
  libs/mocks/src/lib.rs
  libs/mocks/src/pay_fee.rs
  libs/mocks/src/pools.rs
  libs/mocks/src/pre_conditions.rs
  libs/mocks/src/value_provider.rs
  libs/primitives/src/conversion.rs
  libs/traits/src/lib.rs
  libs/types/src/oracles.rs
  pallets/fees/src/lib.rs
  pallets/oracle-data-collection/Cargo.toml
  pallets/oracle-data-collection/src/benchmarking.rs
  pallets/oracle-data-collection/src/lib.rs
  pallets/oracle-data-collection/src/mock.rs
  pallets/oracle-data-collection/src/tests.rs
  pallets/oracle-data-collection/src/weights.rs
  pallets/oracle-feed/Cargo.toml
  pallets/oracle-feed/src/benchmarking.rs
  pallets/oracle-feed/src/lib.rs
  pallets/oracle-feed/src/mock.rs
  pallets/oracle-feed/src/tests.rs
  pallets/oracle-feed/src/weights.rs
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/weights/mod.rs
  runtime/altair/src/weights/pallet_oracle_data_collection.rs
  runtime/altair/src/weights/pallet_oracle_feed.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/weights/mod.rs
  runtime/centrifuge/src/weights/pallet_oracle_data_collection.rs
  runtime/centrifuge/src/weights/pallet_oracle_feed.rs
  runtime/common/Cargo.toml
  runtime/common/src/changes.rs
  runtime/common/src/fees.rs
  runtime/common/src/lib.rs
  runtime/common/src/oracle.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/weights/mod.rs
  runtime/development/src/weights/pallet_oracle_data_collection.rs
  runtime/development/src/weights/pallet_oracle_feed.rs
  runtime/integration-tests/Cargo.toml
Labels: Q5-hard, P5-soon, D2-notify, I8-enhancement

#1658 Loans: Integration with OracleV2
  Cargo.lock
  Cargo.toml
  libs/mocks/src/data.rs
  libs/traits/src/data.rs
  libs/types/src/ids.rs
  pallets/data-collector/Cargo.toml
  pallets/data-collector/src/lib.rs
  pallets/data-collector/src/mock.rs
  pallets/data-collector/src/tests.rs
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/tests/mock.rs
  pallets/loans/src/util.rs
  pallets/oracle-data-collection/src/lib.rs
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/oracle.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/src/generic/cases/loans.rs
  runtime/integration-tests/src/generic/config.rs
  runtime/integration-tests/src/generic/utils/mod.rs
Labels: Q5-hard, P7-asap, I8-enhancement, crcl-protocol

#1661 Oracles: Protect from configuring with duplicated feeders
  pallets/oracle-data-collection/src/benchmarking.rs
  pallets/oracle-data-collection/src/lib.rs
  pallets/oracle-data-collection/src/tests.rs
  runtime/common/src/oracle.rs
  runtime/integration-tests/src/generic/cases/loans.rs
  runtime/integration-tests/src/generic/utils/mod.rs
Labels: I3-annoyance, Q3-medium, P7-asap
