Repository centrifuge/centrifuge-chain, pull requests merged in 2023-01, with the labels that each got.

#1152 Synchronize ensure module with Substrate
  libs/traits/src/ops.rs
  libs/traits/src/rewards.rs
  pallets/liquidity-rewards/src/lib.rs
  pallets/rewards/src/mechanism/base.rs
  pallets/rewards/src/mechanism/deferred.rs
  pallets/rewards/src/mechanism/gap.rs
Labels: D0-ready, crcl-protocol

#1156 Change pool-system event names
  pallets/pool-system/src/impls.rs
  pallets/pool-system/src/lib.rs
Labels: D5-breaks-api

#1159 Add loan actions table documentation
  pallets/loans/src/lib.rs
Labels: I5-documentation, D0-ready, crcl-protocol

#1122 Removes `without_storage_info` macro from pallets
  libs/traits/src/lib.rs
  libs/types/src/epoch.rs
  libs/types/src/fee_keys.rs
  libs/types/src/fixed_point.rs
  libs/types/src/orders.rs
  libs/types/src/permissions.rs
  pallets/anchors/src/lib.rs
  pallets/bridge/src/lib.rs
  pallets/claims/src/lib.rs
  pallets/collator-allowlist/src/lib.rs
  pallets/connectors/src/lib.rs
  pallets/connectors/src/routers.rs
  pallets/crowdloan-claim/src/lib.rs
  pallets/crowdloan-reward/src/lib.rs
  pallets/fees/src/lib.rs
  pallets/interest-accrual/src/lib.rs
  pallets/investments/src/lib.rs
  pallets/investments/src/mock.rs
  pallets/keystore/src/lib.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/loan_type.rs
  pallets/loans/src/mock.rs
  pallets/loans/src/test_utils.rs
  pallets/loans/src/types.rs
  pallets/migration/src/lib.rs
  pallets/nft-sales/src/lib.rs
  pallets/nft/src/lib.rs
  pallets/permissions/src/lib.rs
  pallets/permissions/src/mock.rs
  pallets/pool-registry/src/lib.rs
  pallets/pool-registry/src/mock.rs
  pallets/pool-system/src/impls.rs
  pallets/pool-system/src/lib.rs
  pallets/pool-system/src/mock.rs
  pallets/pool-system/src/pool_types.rs
  pallets/pool-system/src/solution.rs
  pallets/pool-system/src/tranches.rs
  pallets/restricted-tokens/src/lib.rs
  runtime/altair/src/lib.rs
  runtime/common/src/apis/pools.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/xcm/development/tests/connectors.rs
  src/rpc/pools.rs
Labels: D0-ready

#1186 Add `account_for` to `PoolInspect` trait
  libs/traits/src/lib.rs
  pallets/pool-system/src/impls.rs
Labels: D2-notify, crcl-protocol
