Repository centrifuge/centrifuge-chain, pull requests merged in 2023-07, with the labels that each got.

#1364 feat: add connectors v2 extrinsics & inbound msg handlers
  Cargo.lock
  libs/mocks/src/pools.rs
  libs/test-utils/src/mocks/order_manager.rs
  libs/traits/src/connectors.rs
  libs/traits/src/lib.rs
  libs/types/src/domain_address.rs
  libs/types/src/ids.rs
  libs/types/src/tokens.rs
  pallets/connectors/Cargo.toml
  pallets/connectors/src/contract.rs
  pallets/connectors/src/inbound.rs
  pallets/connectors/src/lib.rs
  pallets/connectors/src/message.rs
  pallets/investments/src/lib.rs
  pallets/pool-system/src/impls.rs
  pallets/pool-system/src/tests/mod.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/src/utils/accounts.rs
  runtime/integration-tests/src/utils/mod.rs
  runtime/integration-tests/src/xcm/development/tests/connectors.rs
  runtime/integration-tests/src/xcm/kusama/tests/currency_id_convert.rs
Labels: I8-enhancement

#1432 feat: trait PoolMetadata
  libs/test-utils/src/mocks/orml_asset_registry.rs
  libs/traits/src/lib.rs
  libs/types/src/lib.rs
  libs/types/src/pools.rs
  pallets/investments/Cargo.toml
  pallets/pool-registry/Cargo.toml
  pallets/pool-registry/src/benchmarking.rs
  pallets/pool-registry/src/lib.rs
  pallets/pool-registry/src/mock.rs
  pallets/pool-registry/src/tests.rs
  pallets/pool-system/Cargo.toml
  pallets/pool-system/src/benchmarking.rs
  pallets/pool-system/src/impls.rs
  pallets/pool-system/src/pool_types.rs
  pallets/pool-system/src/tests/mod.rs
  pallets/pool-system/src/tranches.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/utils/pools.rs
  runtime/integration-tests/src/xcm/development/tests/connectors.rs
Labels: D0-ready, I8-enhancement, I6-refactoring

#1444 Fix individual crate compilation issues & add script for running all tests
  Cargo.lock
  ci/script.sh
  libs/mock-builder/Cargo.toml
  libs/traits/Cargo.toml
  pallets/anchors/Cargo.toml
  pallets/bridge/Cargo.toml
  pallets/claims/Cargo.toml
  pallets/connectors/Cargo.toml
  pallets/crowdloan-reward/Cargo.toml
  pallets/investments/Cargo.toml
  pallets/migration/src/benchmarking.rs
  pallets/migration/src/test_data/system_account.rs
  pallets/nft-sales/Cargo.toml
  pallets/nft/Cargo.toml
  pallets/permissions/Cargo.toml
  pallets/pool-registry/src/mock.rs
  pallets/restricted-tokens/Cargo.toml
  pallets/rewards/Cargo.toml
  pallets/transfer-allowlist/Cargo.toml
  runtime/common/Cargo.toml
  scripts/tests.sh
Labels: I3-annoyance, crcl-protocol, dependencies

#1435 Loans: principal and interest separation
  libs/types/src/adjustments.rs
  pallets/loans/docs/types.md
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/entities/interest.rs
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/entities/pricing/internal.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/borrow_loan.rs
  pallets/loans/src/tests/create_loan.rs
  pallets/loans/src/tests/mock.rs
  pallets/loans/src/tests/mod.rs
  pallets/loans/src/tests/mutate_loan.rs
  pallets/loans/src/tests/policy.rs
  pallets/loans/src/tests/portfolio_valuation.rs
  pallets/loans/src/tests/repay_loan.rs
  pallets/loans/src/tests/util.rs
  pallets/loans/src/types/mod.rs
  runtime/common/src/lib.rs
  runtime/integration-tests/src/utils/loans.rs
Labels: Q5-hard, P5-soon, I8-enhancement, D5-breaks-api, crcl-protocol

#1445 Loans: maturity extension support
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/create_loan.rs
  pallets/loans/src/tests/mutate_loan.rs
  pallets/loans/src/tests/util.rs
  pallets/loans/src/types/mod.rs
  runtime/common/src/lib.rs
  runtime/integration-tests/src/utils/loans.rs
Labels: D8-migration

#1446 Update CODEOWNERS file
  .github/CODEOWNERS
Labels: Q0-trivial, D0-ready, P5-soon

#1450 Loans: oracle price as balance
  libs/types/src/adjustments.rs
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/borrow_loan.rs
  pallets/loans/src/tests/close_loan.rs
  pallets/loans/src/tests/create_loan.rs
  pallets/loans/src/tests/mock.rs
  pallets/loans/src/tests/policy.rs
  pallets/loans/src/tests/portfolio_valuation.rs
  pallets/loans/src/tests/repay_loan.rs
  pallets/loans/src/tests/write_off_loan.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
Labels: P7-asap, I6-refactoring, D8-migration

#1443 InterestAccrual: use more flexible interest rate type
  libs/traits/src/interest.rs
  libs/traits/src/lib.rs
  pallets/interest-accrual/src/benchmarking.rs
  pallets/interest-accrual/src/lib.rs
  pallets/interest-accrual/src/migrations.rs
  pallets/interest-accrual/src/mock.rs
  pallets/interest-accrual/src/test_utils.rs
  pallets/interest-accrual/src/tests.rs
  pallets/loans/docs/types.md
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/entities/interest.rs
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/entities/pricing/internal.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/create_loan.rs
  pallets/loans/src/tests/mock.rs
  pallets/loans/src/tests/mod.rs
  pallets/loans/src/tests/mutate_loan.rs
  pallets/loans/src/tests/util.rs
  pallets/loans/src/types/mod.rs
  pallets/loans/src/types/valuation.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/utils/loans.rs
Labels: D5-breaks-api

#1455 Loans: borrow & repay method using pricing-based principal
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/borrow_loan.rs
  pallets/loans/src/tests/close_loan.rs
  pallets/loans/src/tests/mod.rs
  pallets/loans/src/tests/mutate_loan.rs
  pallets/loans/src/tests/policy.rs
  pallets/loans/src/tests/portfolio_valuation.rs
  pallets/loans/src/tests/repay_loan.rs
  pallets/loans/src/tests/util.rs
  pallets/loans/src/tests/write_off_loan.rs
  runtime/integration-tests/src/utils/loans.rs
Labels: P7-asap, I8-enhancement, D5-breaks-api

#1467 Runtime: add `RuntimeChange` version for fast runtimes
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
Labels: I3-annoyance, P9-drop-everything, crcl-protocol
