Repository centrifuge/centrifuge-chain, pull requests merged in 2023-03, with the labels that each got.

#1223 chore: remove unused deps and add missing feats for all tomls
  Cargo.lock
  Cargo.toml
  flake.nix
  libs/primitives/Cargo.toml
  libs/proofs/Cargo.toml
  libs/test-utils/Cargo.toml
  libs/traits/Cargo.toml
  libs/types/Cargo.toml
  libs/utils/Cargo.toml
  pallets/anchors/Cargo.toml
  pallets/bridge-mapping/Cargo.toml
  pallets/bridge/Cargo.toml
  pallets/claims/Cargo.toml
  pallets/collator-allowlist/Cargo.toml
  pallets/connectors/Cargo.toml
  pallets/crowdloan-claim/Cargo.toml
  pallets/crowdloan-reward/Cargo.toml
  pallets/fees/Cargo.toml
  pallets/interest-accrual/Cargo.toml
  pallets/investments/Cargo.toml
  pallets/keystore/Cargo.toml
  pallets/liquidity-rewards/Cargo.toml
  pallets/loans/Cargo.toml
  pallets/migration/Cargo.toml
  pallets/nft-sales/Cargo.toml
  pallets/nft/Cargo.toml
  pallets/permissions/Cargo.toml
  pallets/pool-registry/Cargo.toml
  pallets/pool-system/Cargo.toml
  pallets/restricted-tokens/Cargo.toml
  pallets/rewards/Cargo.toml
  runtime/altair/Cargo.toml
  runtime/centrifuge/Cargo.toml
  runtime/common/Cargo.toml
  runtime/development/Cargo.toml
  runtime/integration-tests/Cargo.toml
  taplo.toml
Labels: D0-ready, I6-refactoring

#1220 Add `mock-builder` to the repo with pools & permissions instances
  .github/CODEOWNERS
  Cargo.lock
  Cargo.toml
  flake.nix
  libs/mock-builder/Cargo.toml
  libs/mock-builder/src/lib.rs
  libs/mock-builder/tests/pallet.rs
  libs/mocks/Cargo.toml
  libs/mocks/src/lib.rs
  libs/mocks/src/permissions.rs
  libs/mocks/src/pools.rs
Labels: D0-ready, crcl-protocol

#1230 Refactor: Fees using a generic pallet mock
  Cargo.lock
  flake.nix
  libs/mock-builder/src/lib.rs
  libs/mocks/src/fees.rs
  libs/mocks/src/lib.rs
  libs/traits/src/lib.rs
  pallets/anchors/Cargo.toml
  pallets/anchors/src/benchmarking.rs
  pallets/anchors/src/mock.rs
  pallets/anchors/src/tests.rs
  pallets/nft/Cargo.toml
  pallets/nft/src/mock.rs
  pallets/nft/src/tests.rs
Labels: D0-ready, P0-someday-maybe, crcl-protocol

#1239 Build CI test in debug
  ci/script.sh
  docs/DEVELOPING.md
Labels: D0-ready, P2-nice-to-have, crcl-cross-chain

#1180 Pallet loan refactor from scratch: `pallet-loans-ref`
  Cargo.lock
  Cargo.toml
  flake.nix
  libs/mocks/src/lib.rs
  libs/mocks/src/permissions.rs
  libs/mocks/src/pools.rs
  pallets/interest-accrual/src/lib.rs
  pallets/interest-accrual/src/tests.rs
  pallets/loans-ref/Cargo.toml
  pallets/loans-ref/src/lib.rs
  pallets/loans-ref/src/mock.rs
  pallets/loans-ref/src/tests.rs
  pallets/loans-ref/src/types.rs
  pallets/loans-ref/src/valuation.rs
  pallets/loans/src/tests.rs
Labels: D9-needsaudit, crcl-protocol

#1242 Pallet loans refactor: essential benchmarks
  Cargo.lock
  flake.nix
  libs/mocks/Cargo.toml
  libs/mocks/src/pools.rs
  libs/traits/src/lib.rs
  pallets/loans-ref/Cargo.toml
  pallets/loans-ref/src/benchmarking.rs
  pallets/loans-ref/src/lib.rs
  pallets/loans-ref/src/mock.rs
  pallets/loans-ref/src/types.rs
  pallets/loans-ref/src/weights.rs
  pallets/pool-system/src/impls.rs
  pallets/pool-system/src/tests/mod.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/weights/mod.rs
  runtime/development/src/weights/pallet_loans_ref.rs
Labels: crcl-protocol

#1248 Pallet loans sustitution in development
  Cargo.lock
  flake.nix
  libs/primitives/src/lib.rs
  pallets/loans-ref/src/lib.rs
  pallets/loans-ref/src/mock.rs
  pallets/loans-ref/src/tests.rs
  pallets/loans-ref/src/types.rs
  pallets/pool-system/src/benchmarking.rs
  pallets/pool-system/src/impls.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/weights/mod.rs
  runtime/development/src/weights/pallet_loans.rs
  runtime/development/src/weights/pallet_loans_ref.rs
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/src/pools/pool_starts.rs
  runtime/integration-tests/src/utils/env.rs
  runtime/integration-tests/src/utils/loans.rs
  runtime/integration-tests/src/utils/pools.rs
  runtime/integration-tests/src/xcm/development/tests/connectors.rs
Labels: D2-notify, crcl-protocol

#1255 Standarize storage names in `pallet-rewards`
  pallets/rewards/src/lib.rs
Labels: Q0-trivial, P5-soon, D5-breaks-api, crcl-protocol

#1260 Pallet loans ref fully benchmarked
  libs/mocks/src/permissions.rs
  libs/mocks/src/pools.rs
  pallets/loans-ref/src/benchmarking.rs
  pallets/loans-ref/src/lib.rs
  pallets/loans-ref/src/types.rs
  pallets/loans-ref/src/weights.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/weights/mod.rs
  runtime/development/src/weights/pallet_loans.rs
  runtime/development/src/weights/pallet_loans_ref.rs
Labels: D0-ready, crcl-protocol

#1262 Rewards mock using `mock-builder`
  Cargo.lock
  flake.nix
  libs/mocks/Cargo.toml
  libs/mocks/src/fees.rs
  libs/mocks/src/lib.rs
  libs/mocks/src/permissions.rs
  libs/mocks/src/pools.rs
  libs/mocks/src/rewards.rs
  libs/mocks/src/template.rs
  libs/traits/Cargo.toml
  libs/traits/src/rewards.rs
  libs/traits/tests/rewards.rs
  pallets/liquidity-rewards/Cargo.toml
  pallets/liquidity-rewards/src/benchmarking.rs
  pallets/liquidity-rewards/src/mock.rs
  pallets/liquidity-rewards/src/tests.rs
Labels: D0-ready, crcl-protocol

#1264 Remove taplo task from tests job
  .github/workflows/tests.yml
Labels: Q0-trivial, D0-ready, I7-optimisation, crcl-protocol

#1274 Pallet loans-ref: Fix policy benchmark
  pallets/loans-ref/src/benchmarking.rs
Labels: D0-ready, crcl-protocol

#1254 Add loans to centrifuge runtime
  Cargo.lock
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/weights/mod.rs
  runtime/centrifuge/src/weights/pallet_loans_ref.rs
Labels: D2-notify, crcl-protocol

#1266 Altair loans sustitution
  Cargo.lock
  Cargo.toml
  flake.nix
  pallets/connectors/Cargo.toml
  pallets/loans-ref/Cargo.toml
  pallets/loans-ref/src/lib.rs
  pallets/loans-ref/src/migrations.rs
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/weights/mod.rs
  runtime/altair/src/weights/pallet_loans.rs
  runtime/altair/src/weights/pallet_loans_ref.rs
Labels: D2-notify, crcl-protocol

#1221 Interest accrual API only with yearly rates
  libs/traits/src/lib.rs
  pallets/interest-accrual/src/lib.rs
  pallets/interest-accrual/src/migrations.rs
  pallets/interest-accrual/src/tests.rs
  pallets/loans-ref/src/benchmarking.rs
  pallets/loans-ref/src/lib.rs
  pallets/loans-ref/src/tests.rs
  pallets/loans-ref/src/types.rs
  pallets/loans-ref/src/valuation.rs
Labels: D5-breaks-api, crcl-protocol
