Repository centrifuge/centrifuge-chain, pull requests merged in 2024-08, with the labels that each got.

#1938 refactor: enable ITs for centrifuge + dev runtimes
  runtime/integration-tests/src/cases/liquidity_pools.rs
  runtime/integration-tests/src/cases/lp/investments.rs
  runtime/integration-tests/src/cases/lp/pool_management.rs
  runtime/integration-tests/src/cases/lp/transfers.rs
Labels: I11-cleaning

#1934 LPv2: Bump-up foreign investment. Fix failing investment ITs
  pallets/foreign-investments/src/entities.rs
  pallets/foreign-investments/src/lib.rs
  pallets/liquidity-pools-gateway/src/lib.rs
  runtime/common/src/evm/mod.rs
  runtime/integration-tests/src/cases/lp/investments.rs
  runtime/integration-tests/src/cases/lp/pool_management.rs
  runtime/integration-tests/src/cases/lp/transfers.rs
  runtime/integration-tests/src/cases/lp/utils.rs
  runtime/integration-tests/src/utils/accounts.rs
Labels: I9-release

#1944 Add increase & decrease debt to borrow proxy
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
Labels: I8-enhancement

#1945 Mock builder update. Improved FI coverage
  Cargo.lock
  libs/mocks/src/foreign_investment_hooks.rs
  libs/mocks/src/token_swaps.rs
  libs/traits/Cargo.toml
  pallets/foreign-investments/src/tests.rs
  pallets/restricted-tokens/Cargo.toml
  runtime/common/Cargo.toml
Labels: I4-tests

#1950 fix: gateway migration et al.
  Cargo.lock
  Cargo.toml
  ci/run-check.sh
  pallets/liquidity-pools-gateway/src/lib.rs
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/migrations.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/src/migrations/foreign_investments_v2.rs
  runtime/common/src/migrations/hold_reason.rs
  runtime/common/src/migrations/liquidity_pools_gateway.rs
  runtime/common/src/migrations/loans.rs
  runtime/common/src/migrations/mod.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/migrations.rs
Labels: I3-annoyance, D8-migration

#1946 migration: Add LP Gateway migration for outbound messages
  Cargo.lock
  Cargo.toml
  ci/run-check.sh
  pallets/liquidity-pools-gateway/src/lib.rs
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/migrations.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/src/migrations/foreign_investments_v2.rs
  runtime/common/src/migrations/hold_reason.rs
  runtime/common/src/migrations/liquidity_pools_gateway.rs
  runtime/common/src/migrations/loans.rs
  runtime/common/src/migrations/mod.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/migrations.rs
Labels: D8-migration

#1952 LPv2: UTs for Batches
  libs/mocks/src/liquidity_pools_gateway_queue.rs
  pallets/liquidity-pools-gateway/src/lib.rs
  pallets/liquidity-pools-gateway/src/tests.rs
Labels: I4-tests

#1947 feat: add freeze & unfreeze extrinsics
  libs/types/src/permissions.rs
  pallets/investments/src/lib.rs
  pallets/investments/src/mock.rs
  pallets/investments/src/tests.rs
  pallets/liquidity-pools/src/defensive_weights.rs
  pallets/liquidity-pools/src/inbound.rs
  pallets/liquidity-pools/src/lib.rs
  pallets/liquidity-pools/src/mock.rs
  pallets/liquidity-pools/src/tests.rs
  pallets/liquidity-pools/src/tests/inbound.rs
  pallets/permissions/src/lib.rs
  runtime/altair/src/lib.rs
  runtime/altair/src/migrations.rs
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/src/lib.rs
  runtime/common/src/migrations/liquidity_pools_gateway.rs
  runtime/common/src/migrations/mod.rs
  runtime/common/src/migrations/permissions_v1.rs
  runtime/common/src/permissions.rs
  runtime/development/src/lib.rs
  runtime/development/src/migrations.rs
  runtime/integration-tests/src/cases/lp/pool_management.rs
  runtime/integration-tests/src/cases/lp/setup_lp.rs
  runtime/integration-tests/src/utils/pool.rs
Labels: I5-documentation, I8-enhancement, D8-migration

#1954 feat: add update tranche hook extrinsic
  pallets/liquidity-pools/src/defensive_weights.rs
  pallets/liquidity-pools/src/lib.rs
  pallets/liquidity-pools/src/mock.rs
  pallets/liquidity-pools/src/tests.rs
  runtime/integration-tests/src/cases/lp/pool_management.rs
Labels: I8-enhancement

#1969 Refactor: Unify DomainAddress and account conversions (r2)
  libs/types/src/domain_address.rs
  libs/types/src/ids.rs
  node/src/chain_spec.rs
  pallets/axelar-router/src/lib.rs
  pallets/axelar-router/src/tests.rs
  pallets/liquidity-pools-gateway/src/lib.rs
  pallets/liquidity-pools-gateway/src/mock.rs
  pallets/liquidity-pools-gateway/src/origin.rs
  pallets/liquidity-pools-gateway/src/tests.rs
  pallets/liquidity-pools/src/hooks.rs
  pallets/liquidity-pools/src/inbound.rs
  pallets/liquidity-pools/src/lib.rs
  pallets/liquidity-pools/src/message.rs
  pallets/liquidity-pools/src/mock.rs
  pallets/liquidity-pools/src/tests.rs
  pallets/liquidity-pools/src/tests/inbound.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/account_conversion.rs
  runtime/common/src/gateway.rs
  runtime/common/src/routing.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/README.md
  runtime/integration-tests/src/cases/example.rs
  runtime/integration-tests/src/cases/liquidity_pools.rs
  runtime/integration-tests/src/cases/liquidity_pools_gateway_queue.rs
  runtime/integration-tests/src/cases/lp/investments.rs
  runtime/integration-tests/src/cases/lp/mod.rs
  runtime/integration-tests/src/cases/lp/pool_management.rs
  runtime/integration-tests/src/cases/lp/setup_evm.rs
  runtime/integration-tests/src/cases/lp/setup_lp.rs
  runtime/integration-tests/src/cases/lp/transfers.rs
  runtime/integration-tests/src/cases/lp/utils.rs
  runtime/integration-tests/src/cases/restricted_transfers.rs
  runtime/integration-tests/src/cases/routers.rs
  runtime/integration-tests/src/config.rs
  runtime/integration-tests/src/envs/evm_env.rs
  runtime/integration-tests/src/envs/fudge_env.rs
  runtime/integration-tests/src/envs/fudge_env/handle.rs
  runtime/integration-tests/src/utils/accounts.rs
  runtime/integration-tests/src/utils/evm.rs
Labels: I6-refactoring

#1977 Split LpMessage traits in subtraits
  libs/traits/src/liquidity_pools.rs
  pallets/liquidity-pools-forwarder/src/lib.rs
  pallets/liquidity-pools-forwarder/src/mock.rs
  pallets/liquidity-pools-gateway/src/lib.rs
  pallets/liquidity-pools-gateway/src/message_processing.rs
  pallets/liquidity-pools-gateway/src/mock.rs
  pallets/liquidity-pools-gateway/src/tests.rs
  pallets/liquidity-pools/src/message.rs
  runtime/common/src/routing.rs
  runtime/integration-tests/src/cases/routers.rs
Labels: I6-refactoring

#1982 Fix: avoid infinite recursion with Message::max_encoded_len()
  pallets/liquidity-pools/src/message.rs
Labels: I2-bug, I12-ci
