Repository centrifuge/centrifuge-chain, pull requests merged in 2024-02, with the labels that each got.

#1716 Gha-upgrades
  .github/workflows/build-docker.yml
  .github/workflows/build-wasm.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/run-benchmarks.yml
Labels: D0-ready

#1717 fix: integration tests for OrderBook market prices
  pallets/foreign-investments/src/entities.rs
  pallets/foreign-investments/src/swaps.rs
  pallets/order-book/src/lib.rs
  runtime/integration-tests/src/generic/cases/liquidity_pools.rs
  runtime/integration-tests/src/generic/config.rs
Labels: I4-tests

#1707 migration: remove claims pallet
  Cargo.lock
  Cargo.toml
  README.md
  libs/types/src/ids.rs
  pallets/claims/Cargo.toml
  pallets/claims/README.md
  pallets/claims/src/lib.rs
  pallets/claims/src/mock.rs
  pallets/claims/src/tests.rs
  pallets/claims/src/weights.rs
  runtime/altair/Cargo.toml
  runtime/altair/src/migrations.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/Cargo.toml
  runtime/common/src/migrations/mod.rs
  runtime/common/src/migrations/nuke.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/integration-tests/Cargo.toml
Labels: D8-migration

#1721 Add asset_registry mock
  Cargo.lock
  libs/mocks/Cargo.toml
  libs/mocks/src/asset_registry.rs
  libs/mocks/src/lib.rs
Labels: Q0-trivial, I4-tests, P0-someday-maybe

#1719 Add typed balances to FI and OrderBook.
  libs/mocks/src/investment.rs
  libs/mocks/src/token_swaps.rs
  libs/traits/src/investments.rs
  libs/traits/src/lib.rs
  libs/types/src/investments.rs
  pallets/foreign-investments/src/entities.rs
  pallets/foreign-investments/src/impls.rs
  pallets/foreign-investments/src/lib.rs
  pallets/foreign-investments/src/mock.rs
  pallets/foreign-investments/src/swaps.rs
  pallets/investments/src/lib.rs
  pallets/investments/src/mock.rs
  pallets/liquidity-pools/src/hooks.rs
  pallets/liquidity-pools/src/lib.rs
  pallets/order-book/src/benchmarking.rs
  pallets/order-book/src/lib.rs
  pallets/order-book/src/mock.rs
  pallets/pool-registry/src/mock.rs
  pallets/pool-system/src/mock.rs
  runtime/altair/src/lib.rs
  runtime/altair/src/liquidity_pools.rs
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/liquidity_pools.rs
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
  runtime/development/src/liquidity_pools.rs
  runtime/integration-tests/src/generic/config.rs
  runtime/integration-tests/src/liquidity_pools/pallet/development/tests/liquidity_pools/setup.rs
Labels: D0-ready, P5-soon, I6-refactoring

#1722 pool fees: explicit handling of zero amounts
  pallets/pool-fees/src/lib.rs
  pallets/pool-fees/src/tests.rs
Labels: D0-ready, I6-refactoring

#1725 Refactor: Use workspace dependencies
  Cargo.lock
  Cargo.toml
  libs/mocks/Cargo.toml
  libs/primitives/Cargo.toml
  libs/proofs/Cargo.toml
  libs/test-utils/Cargo.toml
  libs/traits/Cargo.toml
  libs/types/Cargo.toml
  libs/utils/Cargo.toml
  pallets/anchors/Cargo.toml
  pallets/block-rewards/Cargo.toml
  pallets/bridge/Cargo.toml
  pallets/collator-allowlist/Cargo.toml
  pallets/crowdloan-claim/Cargo.toml
  pallets/crowdloan-reward/Cargo.toml
  pallets/ethereum-transaction/Cargo.toml
  pallets/fees/Cargo.toml
  pallets/foreign-investments/Cargo.toml
  pallets/interest-accrual/Cargo.toml
  pallets/investments/Cargo.toml
  pallets/keystore/Cargo.toml
  pallets/liquidity-pools-gateway/Cargo.toml
  pallets/liquidity-pools-gateway/axelar-gateway-precompile/Cargo.toml
  pallets/liquidity-pools-gateway/routers/Cargo.toml
  pallets/liquidity-pools/Cargo.toml
  pallets/liquidity-rewards/Cargo.toml
  pallets/loans/Cargo.toml
  pallets/migration/Cargo.toml
  pallets/nft-sales/Cargo.toml
  pallets/nft/Cargo.toml
  pallets/order-book/Cargo.toml
  pallets/order-book/src/benchmarking.rs
  pallets/permissions/Cargo.toml
  pallets/pool-fees/Cargo.toml
  pallets/pool-registry/Cargo.toml
  pallets/pool-system/Cargo.toml
  pallets/restricted-tokens/Cargo.toml
  pallets/restricted-xtokens/Cargo.toml
  pallets/rewards/Cargo.toml
  pallets/transfer-allowlist/Cargo.toml
Labels: P5-soon, I6-refactoring

#1728 feat: add PoolFees RtApi & AccruedFees event
  libs/types/src/pools.rs
  pallets/pool-fees/src/lib.rs
  pallets/pool-fees/src/mock.rs
  pallets/pool-fees/src/tests.rs
  pallets/pool-system/src/lib.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/apis/mod.rs
  runtime/common/src/apis/pool_fees.rs
  runtime/development/src/lib.rs
Labels: D2-notify, I8-enhancement

#1730 Remove nft, nft-sales & migration pallets
  Cargo.lock
  Cargo.toml
  libs/types/src/ids.rs
  pallets/liquidity-pools-gateway/routers/Cargo.toml
  pallets/migration/Cargo.toml
  pallets/migration/src/benchmarking.rs
  pallets/migration/src/lib.rs
  pallets/migration/src/mock.rs
  pallets/migration/src/test_data/balances_total_issuance.rs
  pallets/migration/src/test_data/mod.rs
  pallets/migration/src/test_data/proxy_proxies.rs
  pallets/migration/src/test_data/system_account.rs
  pallets/migration/src/test_data/vesting_vesting.rs
  pallets/migration/src/tests.rs
  pallets/migration/src/weights.rs
  pallets/nft-sales/Cargo.toml
  pallets/nft-sales/src/benchmarking.rs
  pallets/nft-sales/src/lib.rs
  pallets/nft-sales/src/mock.rs
  pallets/nft-sales/src/tests.rs
  pallets/nft-sales/src/weights.rs
  pallets/nft/Cargo.toml
  pallets/nft/src/lib.rs
  pallets/nft/src/mock.rs
  pallets/nft/src/tests.rs
  pallets/nft/src/types.rs
  pallets/nft/src/weights.rs
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/migrations.rs
  runtime/altair/src/weights/mod.rs
  runtime/altair/src/weights/pallet_migration_manager.rs
  runtime/altair/src/weights/pallet_nft_sales.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/centrifuge/src/weights/mod.rs
  runtime/centrifuge/src/weights/pallet_migration_manager.rs
  runtime/common/Cargo.toml
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/weights/mod.rs
  runtime/development/src/weights/pallet_migration_manager.rs
  runtime/development/src/weights/pallet_nft_sales.rs
  runtime/integration-tests/Cargo.toml
Labels: P2-nice-to-have, D8-migration, I11-cleaning

#1731 Precompile for balances ERC-20
  Cargo.lock
  Cargo.toml
  ci/run-check.sh
  node/src/chain_spec.rs
  runtime/altair/src/evm.rs
  runtime/centrifuge/src/evm.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/Cargo.toml
  runtime/common/src/evm/precompile.rs
  runtime/common/src/migrations/precompile_account_codes.rs
  runtime/development/src/evm.rs
  runtime/integration-tests/src/evm/precompile.rs
Labels: P5-soon, I8-enhancement

#1737 Cleaning: Repo organization before Polkadot 1.1.0
  Cargo.lock
  Cargo.toml
  libs/mocks/src/token_swaps.rs
  libs/primitives/src/lib.rs
  libs/traits/src/fees.rs
  libs/traits/src/lib.rs
  libs/traits/src/swaps.rs
  node/src/chain_spec.rs
  pallets/foreign-investments/src/entities.rs
  pallets/foreign-investments/src/impls.rs
  pallets/foreign-investments/src/lib.rs
  pallets/foreign-investments/src/tests.rs
  pallets/order-book/src/benchmarking.rs
  pallets/order-book/src/lib.rs
  pallets/order-book/src/mock.rs
  pallets/order-book/src/tests.rs
  pallets/pool-registry/src/mock.rs
  pallets/pool-system/src/mock.rs
  pallets/swaps/src/lib.rs
  pallets/swaps/src/mock.rs
  pallets/swaps/src/tests.rs
  pallets/token-mux/src/benchmarking.rs
  pallets/token-mux/src/lib.rs
  pallets/token-mux/src/tests.rs
  runtime/altair/src/evm.rs
  runtime/altair/src/lib.rs
  runtime/altair/src/xcm.rs
  runtime/centrifuge/src/evm.rs
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/xcm.rs
  runtime/common/Cargo.toml
  runtime/common/src/evm/mod.rs
  runtime/common/src/migrations/local_currency.rs
  runtime/common/src/xcm.rs
  runtime/development/src/evm.rs
  runtime/development/src/lib.rs
  runtime/development/src/xcm.rs
  runtime/integration-tests/src/evm/ethereum_transaction.rs
  runtime/integration-tests/src/evm/precompile.rs
  runtime/integration-tests/src/generic/cases/liquidity_pools.rs
  runtime/integration-tests/src/generic/envs/fudge_env/handle.rs
Labels: Q1-easy, dependencies, I11-cleaning

#1741 Cleaning: Remove `TradingPair`
  libs/mocks/src/investment.rs
  libs/mocks/src/token_swaps.rs
  libs/traits/src/investments.rs
  libs/traits/src/swaps.rs
  pallets/foreign-investments/src/impls.rs
  pallets/investments/src/lib.rs
  pallets/liquidity-pools/src/inbound.rs
  pallets/liquidity-pools/src/lib.rs
  pallets/order-book/src/benchmarking.rs
  pallets/order-book/src/lib.rs
  pallets/order-book/src/mock.rs
  pallets/order-book/src/tests.rs
  pallets/order-book/src/weights.rs
  pallets/swaps/src/lib.rs
  pallets/token-mux/src/benchmarking.rs
  runtime/altair/src/weights/pallet_order_book.rs
  runtime/centrifuge/src/migrations.rs
  runtime/centrifuge/src/weights/pallet_order_book.rs
  runtime/common/src/migrations/local_currency.rs
  runtime/development/src/weights/pallet_order_book.rs
  runtime/integration-tests/src/generic/cases/liquidity_pools.rs
Labels: Q1-easy, P5-soon, D5-breaks-api, I11-cleaning

#1733 Feat: allow borrow automation
  runtime/altair/src/lib.rs
  runtime/altair/src/xcm.rs
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/xcm.rs
  runtime/common/src/xcm.rs
  runtime/development/src/lib.rs
  runtime/development/src/xcm.rs
  runtime/integration-tests/src/generic/cases/account_derivation.rs
  runtime/integration-tests/src/generic/config.rs
  runtime/integration-tests/src/generic/envs/runtime_env.rs
  runtime/integration-tests/src/generic/mod.rs
Labels: D2-notify

#1746 Fix: FI swap correclty with asymmetric ratios
  libs/traits/src/swaps.rs
  pallets/foreign-investments/src/entities.rs
  pallets/foreign-investments/src/impls.rs
  pallets/foreign-investments/src/tests.rs
  pallets/swaps/src/lib.rs
  pallets/swaps/src/tests.rs
Labels: I2-bug, P7-asap, crcl-protocol

#1747 Fix: storage version mismatch + burn-unburned decoding issue
  runtime/altair/src/migrations.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/src/migrations/increase_storage_version.rs
  runtime/common/src/migrations/mod.rs
Labels: D8-migration

#1748 Loans: Runtime API for updating the portfolio with fake prices
  libs/mocks/src/data.rs
  libs/traits/src/data.rs
  pallets/loans/src/entities/input.rs
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/lib.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/apis/loans.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/generic/cases/loans.rs
  runtime/integration-tests/src/generic/config.rs
  runtime/integration-tests/src/generic/envs/runtime_env.rs
  runtime/integration-tests/src/generic/utils/mod.rs
Labels: Q3-medium, P7-asap, I8-enhancement, D5-breaks-api, I6-refactoring, crcl-protocol
