Repository centrifuge/centrifuge-chain, pull requests merged in 2024-07, with the labels that each got.

#1896 Altair: release v0.12.0
  node/src/chain_spec.rs
  runtime/altair/src/weights/pallet_collective.rs
  runtime/altair/src/weights/pallet_collective_council.rs
  runtime/altair/src/weights/pallet_collective_technical_fellowship.rs
  runtime/altair/src/weights/pallet_conviction_voting.rs
  runtime/altair/src/weights/pallet_membership.rs
  runtime/altair/src/weights/pallet_preimage.rs
  runtime/altair/src/weights/pallet_referenda.rs
  runtime/altair/src/weights/pallet_scheduler.rs
  runtime/altair/src/weights/pallet_whitelist.rs
  runtime/development/src/weights/pallet_collective.rs
  runtime/development/src/weights/pallet_collective_council.rs
  runtime/development/src/weights/pallet_collective_technical_fellowship.rs
  runtime/development/src/weights/pallet_conviction_voting.rs
  runtime/development/src/weights/pallet_membership.rs
  runtime/development/src/weights/pallet_preimage.rs
  runtime/development/src/weights/pallet_referenda.rs
  runtime/development/src/weights/pallet_scheduler.rs
  runtime/development/src/weights/pallet_whitelist.rs
Labels: I9-release

#1897 try to succeed job CI failures for codecov
  codecov.yaml
Labels: D0-ready

#1900 Succeed when patch codecov fails
  codecov.yaml
Labels: D0-ready

#1890 Liquidity pools: Add UTs to for `update_token_price()`
  libs/mocks/src/pools.rs
  libs/traits/src/lib.rs
  pallets/liquidity-pools/src/contract.rs
  pallets/liquidity-pools/src/lib.rs
  pallets/liquidity-pools/src/mock.rs
  pallets/liquidity-pools/src/tests.rs
  pallets/pool-system/src/impls.rs
  pallets/pool-system/src/mock.rs
  pallets/pool-system/src/tests/mod.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/oracle.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/cases/liquidity_pools.rs
  runtime/integration-tests/src/cases/lp/pool_management.rs
Labels: I4-tests, crcl-protocol, I11-cleaning

#1902 Clean: remove some unused code from investment trait
  libs/mocks/src/investment.rs
  libs/traits/src/investments.rs
  pallets/investments/src/lib.rs
  runtime/integration-tests/src/cases/liquidity_pools.rs
Labels: I11-cleaning

#1898 Release v0.13.0
  .github/workflows/build-docker.yml
  .github/workflows/build-wasm.yml
  .github/workflows/delete_untagged.yml
  .github/workflows/sanity-checks.yml
  Cargo.lock
  Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/migrations.rs
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/development/src/lib.rs
  runtime/development/src/migrations.rs
  scripts/init.sh
  scripts/js/runtime-upgrade-remote/configs/demo.json
  scripts/js/runtime-upgrade-remote/perform-upgrade.sh
  scripts/run_collator.sh
Labels: I9-release

#1904 Update dependencies
  Cargo.lock
Labels: dependencies

#1905 LP: Add Unitary Tests for update_member()
  pallets/liquidity-pools/src/tests.rs
  runtime/integration-tests/src/cases/liquidity_pools.rs
  runtime/integration-tests/src/cases/lp/pool_management.rs
Labels: I4-tests

#1908 IT: Support `#ignore = reason` for `test_runtimes` macro
  runtime/integration-tests/procedural/src/lib.rs
  runtime/integration-tests/procedural/tests/lib.rs
  runtime/integration-tests/src/lib.rs
Labels: I4-tests

#1910 Lpv2: ignore failing tests
  runtime/integration-tests/src/cases/lp/investments.rs
  runtime/integration-tests/src/cases/lp/transfers.rs
Labels: I4-tests

#1913 ci: disable checks for drafts
  .github/workflows/sanity-checks.yml
Labels: I12-ci

#1912 LP: Unitary testing for add_currency
  libs/types/src/domain_address.rs
  libs/types/src/tokens.rs
  pallets/liquidity-pools/src/lib.rs
  pallets/liquidity-pools/src/tests.rs
  runtime/integration-tests/src/cases/liquidity_pools.rs
Labels: I4-tests

#1918 LPv2: Fix foreign-investments ITs
  runtime/integration-tests/src/cases/liquidity_pools.rs
Labels: I4-tests

#1916 LP: Unitary testing for all pending extrinsics
  pallets/liquidity-pools/src/lib.rs
  pallets/liquidity-pools/src/tests.rs
  runtime/integration-tests/src/cases/liquidity_pools.rs
Labels: I4-tests

#1927 LP: Unitary testing for inbound messages
  pallets/liquidity-pools/src/mock.rs
  pallets/liquidity-pools/src/tests.rs
  pallets/liquidity-pools/src/tests/inbound.rs
Labels: I4-tests

#1928 feat: add domain hook storage
  Cargo.lock
  libs/mocks/src/outbound_queue.rs
  libs/types/src/consts.rs
  pallets/liquidity-pools-gateway/Cargo.toml
  pallets/liquidity-pools-gateway/src/lib.rs
  pallets/liquidity-pools-gateway/src/mock.rs
  pallets/liquidity-pools-gateway/src/tests.rs
  pallets/liquidity-pools/src/lib.rs
  pallets/liquidity-pools/src/mock.rs
  pallets/liquidity-pools/src/tests.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/cases/lp/mod.rs
  runtime/integration-tests/src/cases/lp/pool_management.rs
  runtime/integration-tests/src/cases/lp/setup_lp.rs
Labels: I8-enhancement

#1926 Refactor: Transform `TrancheCurrency` type in a tuple
  libs/mocks/src/pools.rs
  libs/primitives/src/lib.rs
  libs/traits/src/investments.rs
  libs/types/src/tokens.rs
  pallets/foreign-investments/src/mock.rs
  pallets/foreign-investments/src/tests.rs
  pallets/investments/src/benchmarking.rs
  pallets/investments/src/mock.rs
  pallets/liquidity-pools/src/hooks.rs
  pallets/liquidity-pools/src/inbound.rs
  pallets/liquidity-pools/src/lib.rs
  pallets/liquidity-pools/src/mock.rs
  pallets/loans/src/tests/mock.rs
  pallets/pool-fees/src/mock.rs
  pallets/pool-registry/src/benchmarking.rs
  pallets/pool-registry/src/lib.rs
  pallets/pool-registry/src/mock.rs
  pallets/pool-system/src/benchmarking.rs
  pallets/pool-system/src/mock.rs
  pallets/pool-system/src/tests/mod.rs
  pallets/pool-system/src/tests/ratios.rs
  pallets/pool-system/src/tranches.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/cases/investments.rs
  runtime/integration-tests/src/cases/liquidity_pools.rs
  runtime/integration-tests/src/cases/lp/investments.rs
  runtime/integration-tests/src/config.rs
  runtime/integration-tests/src/utils/mod.rs
Labels: I6-refactoring

#1935 refactor: cleanup my leftovers
  pallets/liquidity-pools/src/tests.rs
  runtime/integration-tests/src/cases/lp/setup_lp.rs
Labels: I11-cleaning
