Repository centrifuge/centrifuge-chain, pull requests merged in 2024-05, with the labels that each got.

#1822 commit-test
  .github/workflows/sanity-checks.yml
  ci/run-check.sh
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/build.rs
  runtime/integration-tests/src/generic/utils/evm.rs
Labels: I12-ci

#1834 Remove crowdloan pallets
  Cargo.lock
  Cargo.toml
  libs/proofs/Cargo.toml
  libs/proofs/src/lib.rs
  libs/proofs/src/mock.rs
  libs/proofs/src/tests.rs
  libs/traits/src/lib.rs
  pallets/crowdloan-claim/Cargo.toml
  pallets/crowdloan-claim/README.md
  pallets/crowdloan-claim/src/benchmarking.rs
  pallets/crowdloan-claim/src/lib.rs
  pallets/crowdloan-claim/src/mock.rs
  pallets/crowdloan-claim/src/tests.rs
  pallets/crowdloan-claim/src/weights.rs
  pallets/crowdloan-reward/Cargo.toml
  pallets/crowdloan-reward/README.md
  pallets/crowdloan-reward/src/benchmarking.rs
  pallets/crowdloan-reward/src/lib.rs
  pallets/crowdloan-reward/src/mock.rs
  pallets/crowdloan-reward/src/tests.rs
  pallets/crowdloan-reward/src/weights.rs
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/weights/mod.rs
  runtime/altair/src/weights/pallet_crowdloan_claim.rs
  runtime/altair/src/weights/pallet_crowdloan_reward.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/weights/mod.rs
  runtime/centrifuge/src/weights/pallet_crowdloan_claim.rs
  runtime/centrifuge/src/weights/pallet_crowdloan_reward.rs
  runtime/common/Cargo.toml
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/weights/mod.rs
  runtime/development/src/weights/pallet_crowdloan_claim.rs
  runtime/development/src/weights/pallet_crowdloan_reward.rs
  runtime/integration-tests/Cargo.toml
  scripts/cargo_split.sh
Labels: P5-soon, I11-cleaning

#1837 Fix: transfer debt event with updated repaid amount
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/mod.rs
  pallets/loans/src/tests/repay_loan.rs
  pallets/loans/src/tests/transfer_debt.rs
Labels: I2-bug, P7-asap

#1841 Feat: Add new oracle key
  libs/types/src/oracles.rs
Labels: D0-ready

#1842 Fix: linear accrual not overpassing maturity
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/tests/mod.rs
  pallets/loans/src/tests/repay_loan.rs
Labels: I2-bug, P7-asap

#1838 feat: fix linear pricing migration
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/src/migrations/loans.rs
  runtime/common/src/migrations/mod.rs
  runtime/development/src/migrations.rs
Labels: D8-migration

#1812 Fix/linear pricing
  pallets/loans/src/entities/input.rs
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/mock.rs
  pallets/loans/src/tests/mod.rs
  pallets/loans/src/tests/portfolio_valuation.rs
  pallets/loans/src/tests/repay_loan.rs
  pallets/loans/src/tests/util.rs
  pallets/pool-registry/src/mock.rs
  pallets/pool-system/src/benchmarking.rs
  pallets/pool-system/src/lib.rs
  pallets/pool-system/src/mock.rs
  pallets/pool-system/src/tests/mod.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/src/lib.rs
  runtime/common/src/migrations/loans.rs
  runtime/common/src/migrations/mod.rs
  runtime/common/src/pool.rs
  runtime/development/src/lib.rs
  runtime/development/src/migrations.rs
  runtime/integration-tests/src/generic/cases/loans.rs
  runtime/integration-tests/src/generic/config.rs
Labels: D5-breaks-api, D8-migration

#1845 IT: Add test_runtimes macro to liquidity_pools tests
  runtime/integration-tests/procedural/src/lib.rs
  runtime/integration-tests/src/generic/cases/liquidity_pools.rs
  runtime/integration-tests/src/generic/envs/fudge_env.rs
  runtime/integration-tests/src/generic/envs/runtime_env.rs
  runtime/integration-tests/src/generic/mod.rs
Labels: Q0-trivial, I11-cleaning

#1843 Feat: No maturity date
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/entities/pricing/internal.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/mock.rs
  pallets/loans/src/tests/portfolio_valuation.rs
  pallets/loans/src/tests/util.rs
  pallets/loans/src/types/mod.rs
Labels: D2-notify

#1849 feat: Polkadot v1.7.2 migrations
  runtime/altair/src/migrations.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/src/migrations/hold_reason.rs
  runtime/common/src/migrations/mod.rs
  runtime/development/src/migrations.rs
Labels: D8-migration
