Repository centrifuge/centrifuge-chain, pull requests merged in 2024-04, with the labels that each got.

#1789 Polkadot v1.1.0: Node required changes
  Cargo.lock
  Cargo.toml
  ci/run-check.sh
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/rpc/evm.rs
  node/src/rpc/mod.rs
  node/src/service.rs
  node/src/service/evm.rs
  pallets/rewards/src/migrations/new_instance.rs
  scripts/check_benchmarks.sh
  scripts/runtime_benchmarks.sh
Labels: Q7-very-hard, crcl-protocol

#1776 Polkadot v1.1.0 Integration Tests
  Cargo.lock
  Cargo.toml
  runtime/common/src/xcm.rs
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/src/evm/precompile.rs
  runtime/integration-tests/src/generic/cases/account_derivation.rs
  runtime/integration-tests/src/generic/cases/investments.rs
  runtime/integration-tests/src/generic/cases/liquidity_pools.rs
  runtime/integration-tests/src/generic/cases/loans.rs
  runtime/integration-tests/src/generic/cases/proxy.rs
  runtime/integration-tests/src/generic/config.rs
  runtime/integration-tests/src/generic/env.rs
  runtime/integration-tests/src/generic/envs/fudge_env.rs
  runtime/integration-tests/src/generic/envs/fudge_env/handle.rs
  runtime/integration-tests/src/generic/envs/runtime_env.rs
  runtime/integration-tests/src/generic/impls.rs
  runtime/integration-tests/src/generic/utils/currency.rs
  runtime/integration-tests/src/generic/utils/democracy.rs
  runtime/integration-tests/src/generic/utils/genesis.rs
  runtime/integration-tests/src/utils/accounts.rs
  runtime/integration-tests/src/utils/env.rs
  runtime/integration-tests/src/utils/evm.rs
  runtime/integration-tests/src/utils/extrinsics.rs
  runtime/integration-tests/src/utils/genesis.rs
  rust-toolchain.toml
Labels: I4-tests, Q5-hard

#1745 add code coverage to pipeline
  .github/actions/prep-ubuntu/action.yml
  .github/workflows/codecov.yml
  .github/workflows/xperimental-codecov.yml.commented
  README.md
Labels: D0-ready, I12-ci

#1793 Oracles: Correct feeder encoding
  runtime/common/src/oracle.rs
Labels: Q0-trivial, P4-required

#1794 Remove old migrations and bump up version for centrifuge runtime
  Cargo.lock
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
Labels: Q0-trivial, I9-release, P7-asap, crcl-protocol

#1796 Set correct onchain versions
  runtime/altair/src/migrations.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/src/migrations/increase_storage_version.rs
Labels: Q1-easy, I3-annoyance, P7-asap

#1806 Polkadot v1.1.0: Account converter changes
  node/src/chain_spec.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/account_conversion.rs
  runtime/common/src/gateway.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/generic/cases/liquidity_pools.rs
  runtime/integration-tests/src/utils/evm.rs
Labels: I6-refactoring

#1807 fix: chain spec not deterministic
  node/src/chain_spec.rs
Labels: I2-bug

#1808 fix: polkadot v1.1.0 client
  docs/DEVELOPING.md
  node/src/chain_spec.rs
  node/src/command.rs
  scripts/check_benchmarks.sh
  scripts/export_parachain_files.sh
  scripts/runtime_benchmarks.sh
Labels: I3-annoyance

#1798 fix: essence tranche token metadata
  pallets/pool-system/src/lib.rs
  pallets/pool-system/src/pool_types.rs
  pallets/pool-system/src/tests/mod.rs
Labels: I2-bug

#1800 Remove custom implementation for `MaxEncodingLen`
  pallets/liquidity-pools-gateway/routers/Cargo.toml
  pallets/liquidity-pools-gateway/routers/src/lib.rs
  pallets/liquidity-pools/src/routers.rs
  pallets/pool-system/src/pool_types.rs
Labels: Q1-easy, P2-nice-to-have, I11-cleaning

#1801 Integration tests. Move EVM tests to the generic framework
  runtime/integration-tests/src/evm/ethereum_transaction.rs
  runtime/integration-tests/src/evm/mod.rs
  runtime/integration-tests/src/evm/precompile.rs
  runtime/integration-tests/src/generic/cases/ethereum_transaction.rs
  runtime/integration-tests/src/generic/cases/liquidity_pools.rs
  runtime/integration-tests/src/generic/cases/precompile.rs
  runtime/integration-tests/src/generic/config.rs
  runtime/integration-tests/src/generic/mod.rs
  runtime/integration-tests/src/generic/utils/mod.rs
  runtime/integration-tests/src/lib.rs
Labels: Q3-medium, I4-tests, P5-soon, I6-refactoring, crcl-protocol

#1802 BlockRewards: Fix how it handle ED for Staking currency.
  pallets/block-rewards/src/lib.rs
  pallets/block-rewards/src/mock.rs
  pallets/block-rewards/src/tests.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
Labels: I3-annoyance, Q3-medium, P5-soon, crcl-protocol

#1816 Fix: zero amount order bug
  pallets/foreign-investments/src/tests.rs
  pallets/order-book/src/tests.rs
  pallets/swaps/src/lib.rs
  pallets/swaps/src/tests.rs
Labels: I2-bug, crcl-protocol

#1805 IT: rewards to generic framework. Remove previous non-generic IT utilities
  ci/run-check.sh
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/src/generic/cases/block_rewards.rs
  runtime/integration-tests/src/generic/cases/example.rs
  runtime/integration-tests/src/generic/cases/liquidity_pools.rs
  runtime/integration-tests/src/generic/cases/loans.rs
  runtime/integration-tests/src/generic/cases/rewards.rs
  runtime/integration-tests/src/generic/config.rs
  runtime/integration-tests/src/generic/env.rs
  runtime/integration-tests/src/generic/envs/fudge_env/handle.rs
  runtime/integration-tests/src/generic/envs/runtime_env.rs
  runtime/integration-tests/src/generic/impls.rs
  runtime/integration-tests/src/generic/mod.rs
  runtime/integration-tests/src/generic/utils/genesis.rs
  runtime/integration-tests/src/lib.rs
  runtime/integration-tests/src/rewards/block/env.rs
  runtime/integration-tests/src/rewards/block/invariants.rs
  runtime/integration-tests/src/rewards/block/mod.rs
  runtime/integration-tests/src/rewards/block/session_advances.rs
  runtime/integration-tests/src/rewards/mod.rs
  runtime/integration-tests/src/utils/accounts.rs
  runtime/integration-tests/src/utils/env.rs
  runtime/integration-tests/src/utils/evm.rs
  runtime/integration-tests/src/utils/extrinsics.rs
  runtime/integration-tests/src/utils/genesis.rs
  runtime/integration-tests/src/utils/mod.rs
  runtime/integration-tests/src/utils/time.rs
  runtime/integration-tests/src/utils/tokens.rs
Labels: I4-tests

#1819 fix: undecodable `ForeignInvestmentInfo` on Demo
  Cargo.lock
  pallets/foreign-investments/src/lib.rs
  runtime/common/src/migrations/mod.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/migrations.rs
Labels: I3-annoyance

#1809 fix: pool fee event dispatch order
  pallets/pool-registry/src/lib.rs
  pallets/pool-registry/src/tests.rs
  pallets/pool-system/src/impls.rs
  pallets/pool-system/src/lib.rs
  pallets/pool-system/src/pool_types.rs
  pallets/pool-system/src/tests/mod.rs
Labels: I3-annoyance, D0-ready

#1820 fix: outdated storage versions on Demo
  pallets/block-rewards/src/migrations.rs
  runtime/development/src/migrations.rs
Labels: I3-annoyance

#1821 Integration test: making it cooler!
  Cargo.lock
  Cargo.toml
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/procedural/Cargo.toml
  runtime/integration-tests/procedural/src/lib.rs
  runtime/integration-tests/procedural/tests/lib.rs
  runtime/integration-tests/src/generic/cases/account_derivation.rs
  runtime/integration-tests/src/generic/cases/block_rewards.rs
  runtime/integration-tests/src/generic/cases/ethereum_transaction.rs
  runtime/integration-tests/src/generic/cases/example.rs
  runtime/integration-tests/src/generic/cases/investments.rs
  runtime/integration-tests/src/generic/cases/loans.rs
  runtime/integration-tests/src/generic/cases/oracles.rs
  runtime/integration-tests/src/generic/cases/precompile.rs
  runtime/integration-tests/src/generic/cases/proxy.rs
  runtime/integration-tests/src/generic/cases/restricted_transfers.rs
  runtime/integration-tests/src/generic/mod.rs
  runtime/integration-tests/src/lib.rs
Labels: I4-tests, P2-nice-to-have
