Repository centrifuge/centrifuge-chain, pull requests merged in 2024-03, with the labels that each got.

#1750 fix: bug on oracle fetching
  runtime/centrifuge/src/migrations.rs
  runtime/common/src/oracle.rs
  runtime/integration-tests/src/generic/cases/investments.rs
  runtime/integration-tests/src/generic/cases/loans.rs
  runtime/integration-tests/src/generic/cases/oracles.rs
  runtime/integration-tests/src/generic/cases/proxy.rs
  runtime/integration-tests/src/generic/envs/runtime_env.rs
  runtime/integration-tests/src/generic/mod.rs
  runtime/integration-tests/src/generic/utils/currency.rs
  runtime/integration-tests/src/generic/utils/genesis.rs
Labels: I2-bug, D0-ready

#1758 Feat: Enhance Error Resolution EVM
  pallets/ethereum-transaction/Cargo.toml
  pallets/ethereum-transaction/src/lib.rs
  pallets/ethereum-transaction/src/tests.rs
  pallets/liquidity-pools-gateway/routers/src/tests.rs
  runtime/integration-tests/src/evm/ethereum_transaction.rs
  runtime/integration-tests/src/generic/cases/liquidity_pools.rs
Labels: D2-notify

#1765 Fix: Loans demo migration
  Cargo.lock
  pallets/loans/src/migrations.rs
  runtime/common/src/migrations/increase_storage_version.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/migrations.rs
Labels: I2-bug, P9-drop-everything, D8-migration

#1768 Centrifuge 1026
  Cargo.lock
  node/Cargo.toml
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
Labels: I9-release

#1769 docs: update developing
  docs/DEVELOPING.md
Labels: I5-documentation

#1772 Post RU: Remove old migrations and bump up versions
  Cargo.lock
  pallets/block-rewards/src/migrations.rs
  pallets/loans/src/entities/loans.rs
  pallets/loans/src/entities/pricing/external.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/migrations.rs
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/migrations.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/src/migrations/asset_registry_xcmv3.rs
  runtime/common/src/migrations/epoch_execution.rs
  runtime/common/src/migrations/local_currency.rs
  runtime/common/src/migrations/mod.rs
  runtime/common/src/migrations/orml_tokens.rs
  runtime/common/src/migrations/transfer_allowlist_currency.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/migrations.rs
Labels: Q1-easy

#1773 Fix: order book working with local currencies
  libs/traits/src/lib.rs
  pallets/order-book/src/benchmarking.rs
  pallets/order-book/src/lib.rs
  pallets/order-book/src/mock.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
Labels: I2-bug, D0-ready, P9-drop-everything

#1774 fix: permit token mux calls for `ProxyType::Borrow`
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/development/src/lib.rs
Labels: I3-annoyance, P7-asap

#1735 Add try-runtime to ci pipeline
  .github/workflows/try-runtime.yml
  ci/run-check.sh
Labels: D0-ready, I12-ci, github_actions

#1778 Rewards: move rewards api tests to generic testing
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/lib.rs
  runtime/development/src/lib.rs
  runtime/integration-tests/src/generic/cases/rewards.rs
  runtime/integration-tests/src/generic/config.rs
  runtime/integration-tests/src/generic/mod.rs
  runtime/integration-tests/src/lib.rs
  runtime/integration-tests/src/runtime_apis/mod.rs
  runtime/integration-tests/src/runtime_apis/rewards.rs
Labels: Q3-medium, I4-tests, P7-asap
