Repository centrifuge/centrifuge-chain, pull requests merged in 2024-01, with the labels that each got.

#1662 Integration tests for proxies
  runtime/integration-tests/src/generic/cases/liquidity_pools.rs
  runtime/integration-tests/src/generic/cases/proxy.rs
  runtime/integration-tests/src/generic/config.rs
  runtime/integration-tests/src/generic/envs/fudge_env/handle.rs
  runtime/integration-tests/src/generic/mod.rs
  runtime/integration-tests/src/generic/utils/currency.rs
Labels: Q3-medium, I4-tests, P2-nice-to-have

#1670 Oracles: Time validation by a max age threshold
  libs/mocks/src/data.rs
  libs/traits/src/data.rs
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/portfolio_valuation.rs
  pallets/oracle-data-collection/src/benchmarking.rs
  pallets/oracle-data-collection/src/lib.rs
  pallets/oracle-data-collection/src/mock.rs
  pallets/oracle-data-collection/src/tests.rs
  pallets/oracle-data-collection/src/weights.rs
  runtime/altair/src/lib.rs
  runtime/altair/src/weights/pallet_oracle_data_collection.rs
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/weights/pallet_oracle_data_collection.rs
  runtime/development/src/lib.rs
  runtime/development/src/weights/pallet_oracle_data_collection.rs
Labels: D0-ready, Q3-medium, P7-asap, I8-enhancement

#1671 Rename from `pallet-oracle-data-collection` to `pallet-oracle-collection`
  Cargo.lock
  Cargo.toml
  pallets/oracle-collection/Cargo.toml
  pallets/oracle-collection/src/benchmarking.rs
  pallets/oracle-collection/src/lib.rs
  pallets/oracle-collection/src/mock.rs
  pallets/oracle-collection/src/tests.rs
  pallets/oracle-collection/src/weights.rs
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/weights/mod.rs
  runtime/altair/src/weights/pallet_oracle_collection.rs
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/weights/mod.rs
  runtime/centrifuge/src/weights/pallet_oracle_collection.rs
  runtime/common/Cargo.toml
  runtime/common/src/changes.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/weights/mod.rs
  runtime/development/src/weights/pallet_oracle_collection.rs
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/src/generic/config.rs
  runtime/integration-tests/src/generic/utils/mod.rs
Labels: Q0-trivial, P7-asap, I6-refactoring, crcl-protocol

#1659 remarks: Add remarks pallet
  Cargo.lock
  Cargo.toml
  runtime/centrifuge/Cargo.toml
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/weights/mod.rs
  runtime/centrifuge/src/weights/pallet_remarks.rs
  runtime/common/src/lib.rs
  runtime/common/src/remarks.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/weights/mod.rs
  runtime/development/src/weights/pallet_remarks.rs
Labels: D0-ready, P7-asap, I8-enhancement

#1688 Development 1037
  Cargo.lock
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/migrations.rs
Labels: D0-ready

#1691 Loans: add `increase_debt()` action
  pallets/loans/src/benchmarking.rs
  pallets/loans/src/lib.rs
  pallets/loans/src/tests/borrow_loan.rs
  pallets/loans/src/weights.rs
  runtime/altair/src/weights/pallet_loans.rs
  runtime/centrifuge/src/weights/pallet_loans.rs
  runtime/development/src/weights/pallet_loans.rs
Labels: Q3-medium, P7-asap, I8-enhancement, crcl-protocol

#1660 Minor Docker enhancements
  .github/workflows/build-docker.yml
  docker/centrifuge-chain/Dockerfile
Labels: Q0-trivial, D0-ready

#1695 fix: correct epoch execution with fees
  Cargo.lock
  pallets/pool-system/src/lib.rs
  pallets/pool-system/src/solution.rs
  pallets/pool-system/src/tests/mod.rs
  runtime/altair/src/migrations.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/src/migrations/epoch_execution.rs
  runtime/common/src/migrations/mod.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
  runtime/development/src/migrations.rs
Labels: D2-notify, D8-migration

#1693 Fix: Limitations of Transfer Allowlist
  libs/traits/src/lib.rs
  libs/types/src/locations.rs
  libs/types/src/tokens.rs
  pallets/transfer-allowlist/src/benchmarking.rs
  pallets/transfer-allowlist/src/lib.rs
  pallets/transfer-allowlist/src/mock.rs
  pallets/transfer-allowlist/src/tests.rs
  runtime/altair/src/lib.rs
  runtime/altair/src/migrations.rs
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/migrations.rs
  runtime/common/src/migrations/mod.rs
  runtime/common/src/migrations/transfer_allowlist_currency.rs
  runtime/common/src/transfer_filter.rs
  runtime/development/src/lib.rs
  runtime/development/src/migrations.rs
  runtime/integration-tests/src/generic/cases/liquidity_pools.rs
  runtime/integration-tests/src/generic/config.rs
  runtime/integration-tests/src/generic/env.rs
  runtime/integration-tests/src/generic/envs/runtime_env.rs
  runtime/integration-tests/src/utils/extrinsics.rs
Labels: D5-breaks-api

#1701 Fix: pool-registry test compilation
  pallets/pool-registry/src/mock.rs
Labels: I3-annoyance, I4-tests, P7-asap

#1698 FI v2: refactor without states
  Cargo.lock
  libs/traits/src/investments.rs
  libs/types/src/investments.rs
  pallets/foreign-investments/Cargo.toml
  pallets/foreign-investments/src/entities.rs
  pallets/foreign-investments/src/errors.rs
  pallets/foreign-investments/src/hooks.rs
  pallets/foreign-investments/src/impls.rs
  pallets/foreign-investments/src/impls/benchmark_utils.rs
  pallets/foreign-investments/src/impls/invest.rs
  pallets/foreign-investments/src/impls/mod.rs
  pallets/foreign-investments/src/impls/redeem.rs
  pallets/foreign-investments/src/lib.rs
  pallets/foreign-investments/src/mock.rs
  pallets/foreign-investments/src/swaps.rs
  pallets/foreign-investments/src/tests.rs
  pallets/foreign-investments/src/types.rs
  pallets/investments/src/lib.rs
  pallets/investments/src/mock.rs
  pallets/liquidity-pools/src/benchmarking.rs
  pallets/liquidity-pools/src/hooks.rs
  pallets/liquidity-pools/src/inbound.rs
  pallets/liquidity-pools/src/lib.rs
  pallets/liquidity-pools/src/weights.rs
  pallets/order-book/src/lib.rs
  pallets/order-book/src/tests.rs
  pallets/pool-registry/src/mock.rs
  pallets/pool-system/src/mock.rs
  runtime/altair/src/lib.rs
  runtime/altair/src/liquidity_pools.rs
  runtime/centrifuge/src/lib.rs
  runtime/centrifuge/src/liquidity_pools.rs
  runtime/development/src/lib.rs
  runtime/development/src/liquidity_pools.rs
  runtime/integration-tests/src/generic/cases/liquidity_pools.rs
  runtime/integration-tests/src/generic/config.rs
Labels: P7-asap, I6-refactoring

#1705 fix: foreign investment amount
  pallets/foreign-investments/src/impls.rs
  pallets/foreign-investments/src/tests.rs
Labels: I2-bug

#1702 Fix: transfer filters
  Cargo.lock
  runtime/altair/Cargo.toml
  runtime/altair/src/lib.rs
  runtime/altair/src/weights/mod.rs
  runtime/altair/src/weights/pallet_remarks.rs
  runtime/common/Cargo.toml
  runtime/common/src/transfer_filter.rs
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/src/generic/cases/restricted_transfers.rs
  runtime/integration-tests/src/generic/config.rs
  runtime/integration-tests/src/generic/envs/runtime_env.rs
  runtime/integration-tests/src/generic/mod.rs
Labels: D0-ready

#1706 refactor: assign pool fee id during propose
  Cargo.lock
  pallets/pool-fees/src/benchmarking.rs
  pallets/pool-fees/src/lib.rs
  pallets/pool-fees/src/mock.rs
  pallets/pool-fees/src/tests.rs
  pallets/pool-fees/src/types.rs
  runtime/common/src/changes.rs
Labels: I3-annoyance, D2-notify

#1703 feat: add NAV runtime API
  Cargo.lock
  libs/types/src/pools.rs
  runtime/altair/src/lib.rs
  runtime/centrifuge/src/lib.rs
  runtime/common/src/apis/pools.rs
  runtime/development/Cargo.toml
  runtime/development/src/lib.rs
Labels: D2-notify, I8-enhancement
